<a href="https://colab.research.google.com/github/borisdev/borisdev.github.io/blob/master/boris_case_generation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Enter credentials to access a Casescope/Casemaker Apis.

In [32]:
from getpass import getpass

email = input("Email: ")
password = getpass("Password: ")

Email: boris@wolfgames.ai
Password: ··········

Authenticating and getting auth token

Requesting prompt "case_common_info" generating a Case.

In [33]:
import requests
import pprint
from IPython.display import Markdown as md


response = requests.post("https://auth.casescope.com/auth/signin", {"email": email, "password": password})

print(response.status_code)
print(response)
auth_data = response.json()
print(auth_data)
access_token = auth_data['accessToken']
pp = pprint.PrettyPrinter(indent=1)
#pp.pprint(auth_data)
print(f"Auth Token: {access_token}")

201

<Response [201]>

{
    'accessToken':
'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkiLCJlbWFpbCI6ImJvcmlzQHdvbGZnYW1lcy5haSIsInN1YiI6ImY1ZjcyZjE3LTVmM
mYtNDc3OS05OTQyLTIxNjIxMmFhZTNkYyIsInJvbGVzIjpbIlVTRVIiLCJTVVBFUl9BRE1JTiJdLCJpYXQiOjE3MDI0OTE4MzgsImV4cCI6MTcwMjU3
ODIzOH0.tJZxBSaqa8ThWVIdjdEGkKN3efbfZWABHlrDmx1_u7py2TuoVwvyGqg3IkpgqpZreDreddOfl8M6lI3z1-_9ZgAxfi6Ac_ySQEif11koJbn
LpMa_qbQj3_a5drcoLkRRhYyvHbzP3Rf00COLqWSXAEm9DqwXRWnoHy8H0GLoPQ_SR-fUdZ07Q01-CJ39PWU92yed55NSfdOus4SP8shlwukL4nZP5l
Gz-hd03HuAKDNPcUdYwgVXJhcxdnN0iiM6GJwnObVxvMbktaxaIeoNqFUHyFyP4n9YXKVwlaghOrunxVj-6-b0MAMqoFPxmrd_m66FYhrcoYKaOayDI
4BCqCotPZvmvlWPQtptHMcYLlIDNBSXjpQZQXn4zQtB26BcJuebRai1JvPqku8-hDWuFx3kgdXtJuBrbgf6KlJ9ofe64v9K7ODfqvbjZXWqL_XR2lS6
af76l90_NVypV5dNKb6tMvcpnYWUrXSoh0fkseLv6Jrw5rPbF0niPgb-URyvhNVIk2dnDME2IHGHpmPecGC7PrOW9KfGiGzcOSvAbDq5eaJ2YunVaim
2wqH1ZHjm_ah6YOuVgLuY85-Jw2IHhc7wYQ6qoK-77zxkwUiMDxYkXt0oyi2_f5LjpS1ZAYbWxaTER8QVmuO8vilyBYGFUcTshXrxVqsmDmO_1fsdpF
s',
    'refreshToken':
'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkiLCJlbWFpbCI6ImJvcmlzQHdvbGZnYW1lcy5haSIsInN1YiI6ImY1ZjcyZjE3LTVmM
mYtNDc3OS05OTQyLTIxNjIxMmFhZTNkYyIsInJvbGVzIjpbIlVTRVIiLCJTVVBFUl9BRE1JTiJdLCJpYXQiOjE3MDI0OTE4MzgsImV4cCI6MTcwMjU3
ODIzOH0.R8sLOGpHqS9DuO3pRWsD1jeXcXT3a4EjDG2rKioGIP0',
    'expiresIn': 86400
}

Auth Token:
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkiLCJlbWFpbCI6ImJvcmlzQHdvbGZnYW1lcy5haSIsInN1YiI6ImY1ZjcyZjE3LTVmMm
YtNDc3OS05OTQyLTIxNjIxMmFhZTNkYyIsInJvbGVzIjpbIlVTRVIiLCJTVVBFUl9BRE1JTiJdLCJpYXQiOjE3MDI0OTE4MzgsImV4cCI6MTcwMjU3O
DIzOH0.tJZxBSaqa8ThWVIdjdEGkKN3efbfZWABHlrDmx1_u7py2TuoVwvyGqg3IkpgqpZreDreddOfl8M6lI3z1-_9ZgAxfi6Ac_ySQEif11koJbnL
pMa_qbQj3_a5drcoLkRRhYyvHbzP3Rf00COLqWSXAEm9DqwXRWnoHy8H0GLoPQ_SR-fUdZ07Q01-CJ39PWU92yed55NSfdOus4SP8shlwukL4nZP5lG
z-hd03HuAKDNPcUdYwgVXJhcxdnN0iiM6GJwnObVxvMbktaxaIeoNqFUHyFyP4n9YXKVwlaghOrunxVj-6-b0MAMqoFPxmrd_m66FYhrcoYKaOayDI4
BCqCotPZvmvlWPQtptHMcYLlIDNBSXjpQZQXn4zQtB26BcJuebRai1JvPqku8-hDWuFx3kgdXtJuBrbgf6KlJ9ofe64v9K7ODfqvbjZXWqL_XR2lS6a
f76l90_NVypV5dNKb6tMvcpnYWUrXSoh0fkseLv6Jrw5rPbF0niPgb-URyvhNVIk2dnDME2IHGHpmPecGC7PrOW9KfGiGzcOSvAbDq5eaJ2YunVaim2
wqH1ZHjm_ah6YOuVgLuY85-Jw2IHhc7wYQ6qoK-77zxkwUiMDxYkXt0oyi2_f5LjpS1ZAYbWxaTER8QVmuO8vilyBYGFUcTshXrxVqsmDmO_1fsdpFs

In [34]:
casescope_url = "https://api.casescope.com"
headers = {"Authorization": f"Bearer {access_token}"}

def get_prompt(prompt_id: int):
  response = requests.get(f"{casescope_url}/ai_prompt/{prompt_id}", headers=headers)
  data = response.json()
  prompt = data["prompt"]
  print(f"Prompt: {prompt}")
  return prompt

# Boris's new code

- New events
- Evaluiation as a events timeline table

In [51]:
def get_new_events(synopsis: str, characters: list[dict]):
    data = dict(
        synopsis=synopsis,
        characters=characters
    )
    # TODO default to GPT4 with option parameter to GPT3 for speed
    event_endpoint = "https://causal-graph.casescope.com/events"

    r = requests.post(event_endpoint, json=data)
    print(r.status_code)
    data = r.json()
    return data

# Code to make timeline for evaluation of events

def events2df(events):
    character2events = {}

    for event in events:
        characters = event["characters"]
        for character in characters:
            if character not in character2events:
                character2events[character] = {
                    "character": character,
                    -6: "",
                    -5: "",
                    -4: "",
                    -3: "",
                    -2: "",
                    -1: "",
                    0: "",
                }
            era = event["era"]
            character2events[character][era] = (
                event["name"] + "\n\n" + event["description"] + "\n\n" + event["job"]
            )

    # print(character2events)

    df = pd.DataFrame(character2events.values())
    df = df[["character", -6, -5, -4, -3, -2, -1, 0]]
    return df

def pretty_print(df):
    return display(HTML(df.to_html().replace("\\n", "<br>")))

def events2timeline(events):
    df = events2df(events)
    pretty_print(df)

def oldevents2df(events):
    character2events = {}
    eras = []

    for event in events:
        character = event["charactersOnCasesUid"]

        if character not in character2events:
            character2events[character] = {"character": character}
        era = event["era"]
        eras.append(era)
        character2events[character][era] = event["name"] + "\n\n" + event["description"]

    # print(character2events)

    df = pd.DataFrame(character2events.values())
    sorted_eras = sorted(set(eras))
    df = df[["character"] + sorted_eras]
    return df

def oldevents2timeline(events):
    df = oldevents2df(events)
    pretty_print(df)

# Marisol case test input data

In [36]:
# source: casemaker
marisol_synopsis =  "### Synopsis\n\nMarisol Vega, a young woman thriving in her career as a Sustainable Design Consultant, suffered a tragic end when she was strangled to death at her San Francisco residence. On September 9th, 2023, at 1466 34th Ave in the Northern Police District, her life was claimed. Her sister, Juanita Vega, a local educator, found her lifeless body and in distress, she called the authorities at 10:47 PM. Prior to the murder, Marisol had visited \"The Gilded Palace,\" a bar where an altercation escalated from a past grievance with Alex Duran, the bartender on duty that night. \n\nMarisol Vega had been enjoying a seemingly ordinary evening up until her final moments. The incident occurred within a timeframe when long-standing tensions reached their pinnacle, involving personal relationships tainted by jealousy, spite, and disillusionment among her closest circles. This set of complex dynamics and interactions underlined the fateful outcome that conspired to end her life.\n\n### Characters\n\n**Victim: Marisol Vega**\nA lively and ambitious Sustainable Design Consultant, Marisol Vega was in her early thirties with a passion for eco-friendly living and innovative urban development.\n\n**Suspect_1: Alex Duran**\nA bartender with a history of minor criminal conduct, Alex Duran's aggressive tendencies have been recorded more than once. He was on shift at \"The Gilded Palace\" the night Marisol Vega visited.\n\n**Suspect_2: Rose Hawthorne**\nRose Hawthorne is the estranged ex-girlfriend of Marisol Vega, known for her volatile temperament and a life increasingly characterized by solitude and bitterness after the relationship's collapse.\n\n**Suspect_3: Leonel Graves**\nLeonel Graves, once a member of Marisol's inner circle, turned adversary due to exclusion from the group, bears a heavy burden of enmity towards Vega.\n\n**Witness: Juanita Vega**\nAs Marisol Vega's sister and housemate, Juanita Vega is an educator whose routine night was shattered upon discovering the tragic demise of her sibling. \n\n### **Means, Motive & Opportunity**\n\n**Means:** The victim was killed using a length of high-tensile strength nylon rope (Gladiator Pro-Grade Climbing Rope, SKU# GPR-7560), utilized expertly in a strangulation.\n\n**Motive:** \n- **Suspect_1:** Fueled by a mixture of envy over Vega's success, and a reignited argument from their past, Duran's long-standing impulse control issues could point to a motive.\n- **Suspect_2:** Hawthorne's repeated attempts to thwart Vega\u2019s romantic endeavors stemmed from endless jealousy and a desire to rekindle past flames, indicating possible motives.\n- **Suspect_3:** Graves's plummet into morosity and subsequent fantasies of retribution after being distanced from the friend group display clear motives of resentment and revenge.\n\n**Opportunity:**\n- **Suspect_1:** The last person to see Vega at his place of work, Duran had both the chance and the familiarity with Vega's routines to follow her home.\n- **Suspect_2:** Living within walking distance of Vega's home, Hawthorne had easy access to the crime scene and knowledge of Vega's whereabouts.\n- **Suspect_3:** Graves was observed nearby the murder location on the evening in question, having serendipitously run into Vega, placing him close to the victim mere hours before her death.\n\n### The Night Of\n\nOn the night of September 9th, 2023, Marisol Vega chose to unwind at \"The Gilded Palace\" bar, not knowing that it would be her final outing. While there, she encountered Alex Duran, a bartender whose mood darkened with every minute she spent at the establishment due to their past disputes. Despite their brief interaction, the encounter reinvoked tensions and as the night drew on, Duran's irritation with Vega became unmistakable rage. \n\nAfter Vega departed, Duran, unable to shake his anger, trailed her home. Meanwhile, suspicion could have easily turned toward Leonel Graves, who watched Vega from the shadows, embodying the quintessence of a bitter ex-associate. However, it was Alex Duran, driven by uncontrolled fury, who pursued and seized his opportunity to force himself into Vega\u2019s residence. Once inside, he employed a nylon rope to strangle the life out of Marisol Vega\u2014an act that brought a disturbing calm to his chaotic sentiments.\n\nNearby, Rose Hawthorne, Vega\u2019s former romantic partner, was ensnared by her own vices, oblivious to the crime unfurling mere blocks away. Juanita Vega\u2019s night, characterized by a serene date, became a nightmare upon returning home to a crime scene. It was a disturbing convergence of opportunity, motive, and unchecked anger that led to Marisol Vega's untimely demise at the hands of Alex Duran. The evidence collected by law enforcement, coupled with Duran's observable agitation that night, would later cement his culpability in the gruesome act."

In [37]:
# source: ran casescope events chain with above synopsis
marisol_characters = [
    {
      "sex": "male",
      "role": "Culprit",
      "age": 32,
      "occupation": "Bartender",
      "firstName": "Alex",
      "lastName": "Duran",
      "vices": [
        "aggression",
        "impulse control",
        "jealousy"
      ],
      "relationships": [
        {
          "role": "Victim",
          "type": "academism",
          "name": "Marisol Vega"
        }
      ],
      "description": "Alex Duran, a 32-year-old Latino bartender known for his wiry build and unmistakeable black hair, has a history of minor criminal conduct marked by aggressive tendencies. His dark brown eyes always hold a grudge. He was on shift at The Gilded Palace the night Marisol Vega visited. Alex has always shown signs of envy for those more successful than him, and his stint in jail for assault only seemed to harden his bitter outlook."
    },
    {
      "sex": "female",
      "role": "Witness",
      "age": 38,
      "occupation": "Grade School Teacher",
      "firstName": "Juanita",
      "lastName": "Vega",
      "vices": [
        "overprotectiveness"
      ],
      "relationships": [
        {
          "role": "Victim",
          "type": "sister",
          "name": "Marisol Vega"
        }
      ],
      "description": "Juanita Vega, aged 38, is a local elementary school teacher known for her conservative attire and caring manner. She has dark curly hair, a petite figure, and her glasses always rest on the tip of her nose. Despite a pleasant demeanor, Juanita is overprotective of her younger sister, Marisol, frequently voicing disapproval of her lifestyle. Her cool-headed outlook on life was shattered upon discovering Marisol's tragic death."
    },
    {
      "sex": "female",
      "role": "Suspect",
      "age": 28,
      "occupation": "Surgeon",
      "firstName": "Rose",
      "lastName": "Hawthorne",
      "vices": [
        "jealousy",
        "manipulative",
        "condescending"
      ],
      "relationships": [
        {
          "role": "Victim",
          "type": "ex-girlfriend",
          "name": "Marisol Vega"
        }
      ],
      "description": "Dr. Rose Hawthorne, a 28-year-old Cardiothoracic Surgeon, is an imposing figure with stark, contrasting features. Her fiery red hair and icy blue eyes exemplify her volatile temperament. An estranged ex-girlfriend of Marisol Vega, Rose struggles with profound jealousy, a constant fissure from their collapsed relationship. This amalgamation of bitterness and life in solitude pushes her towards manipulative tactics to control Marisol's life post their breakup."
    },
    {
      "sex": "male",
      "role": "Suspect",
      "age": 33,
      "occupation": "Event Planner",
      "firstName": "Leonel",
      "lastName": "Graves",
      "vices": [
        "resentment",
        "bitterness"
      ],
      "relationships": [
        {
          "role": "Victim",
          "type": "former friend",
          "name": "Marisol Vega"
        }
      ],
      "description": "Leonel Graves, a 33-year-old Event Planner, is a quick-thinker known for his innovative approaches to his profession. Leonel, with his lonesome brown eyes and a thinning black beard, was once a valued member in Marisol's circle of friends. His exclusion from the group plunged him into a potent cocktail of bitterness and resentment, which fuels an unshakeable aspiration for retribution against Marisol Vega."
    },
    {
      "sex": "female",
      "role": "Victim",
      "age": 31,
      "occupation": "Sustainable Design Consultant",
      "firstName": "Marisol",
      "lastName": "Vega",
      "vices": [
        "stubbornness"
      ],
      "relationships": [
        {
          "role": "Witness",
          "type": "sister",
          "name": "Juanita Vega"
        },
        {
          "role": "Culprit",
          "type": "known",
          "name": "Alex Duran"
        },
        {
          "role": "Suspect",
          "type": "ex-girlfriend",
          "name": "Rose Hawthorne"
        },
        {
          "role": "Suspect",
          "type": "colleague",
          "name": "Leonel Graves"
        }
      ],
      "description": "Marisol Vega, 31-year-old, was a lively yet stubborn Sustainable Design Consultant with dreams of eco-friendly living and innovative urban development. She was known for her striking beauty, characterized by dark-curled hair and expressive green eyes that mirrored her world-saving aspirations."
    }
  ]

# Run new events service against the Marisol case

In [38]:
# TEST
marisol_new_events = get_new_events(synopsis=marisol_synopsis, characters=marisol_characters)
print(marisol_new_events)
events2timeline(marisol_new_events)

200

[
    {
        'category': 'EVENT',
        'characters': ['Marisol Vega', 'Alex Duran'],
        'charactersOnCasesUid': '',
        'datetime': 'PLACEHOLDER',
        'description': "On September 9th, 2023, Marisol Vega was found strangled to death at her residence. The
murder weapon was a high-tensile strength nylon rope. Alex Duran, a bartender with a history of aggression,
followed Vega home from The Gilded Palace after an altercation. Duran entered the residence and strangled Vega with
the nylon rope. Rose Hawthorne, Vega's ex-girlfriend, and Leonel Graves, a former friend, were also considered
suspects due to proximity and motive, but evidence pointed to Duran. Juanita Vega, the victim's sister, discovered
the body upon returning home from a date.",
        'era': 0,
        'job': '',
        'name': 'Murder scene: Alex Duran kills Marisol Vega'
    },
    {
        'category': 'EVENT',
        'characters': ['Marisol Vega'],
        'charactersOnCasesUid': '',
        'datetime': 'PLACEHOLDER',
        'description': "Marisol Vega, a 31-year-old Marketing Consultant, lived in New York City. Born and raised
in a middle-class neighborhood, Marisol attended public schools and graduated with honors from college. She worked
at a mid-sized marketing firm where she was known for her strategic thinking and leadership skills. Marisol enjoyed
a wide social circle and was often the organizer of group activities. Despite her busy professional life, she found
time to volunteer at local charities, focusing on community development and youth programs. Her relationship with
Rose Hawthorne lasted two years before ending abruptly due to personal differences. Marisol's social circle
included Leonel Graves until a falling out occurred, leading to his exclusion from the group. Marisol lived alone
in an apartment she purchased two years prior to her death.",
        'era': -6,
        'job': '',
        'name': 'Marisol Vega: victim start scene'
    },
    {
        'category': 'OPPORTUNITY',
        'characters': ['Rose Hawthorne'],
        'charactersOnCasesUid': '',
        'datetime': 'PLACEHOLDER',
        'description': "Dr. Rose Hawthorne, a 28-year-old Cardiothoracic Surgeon, could not have had the
opportunity to commit the murder of Marisol Vega. On the night of September 9th, 2023, Dr. Hawthorne was on duty at
the hospital, performing a complex and time-consuming open-heart surgery. The procedure was scheduled from 7 PM to
1 AM, which overlaps with the estimated time of Marisol Vega's death. The surgery was documented, and the
hospital's records confirm Dr. Hawthorne's presence in the operating room throughout the entire duration.
Additionally, multiple colleagues and the surgical team can attest to her involvement in the operation, thus
providing her with a solid alibi. The surgical procedure and the hospital environment are monitored and secure,
making it impossible for Dr. Hawthorne to leave unnoticed. Therefore, it is clear that Dr. Rose Hawthorne could not
have been at the crime scene and thus did not have the opportunity to commit the murder.",
        'era': 0,
        'job': 'Rose Hawthorne truth opp',
        'name': 'Rose Hawthorne had no opportunity'
    },
    {
        'category': 'OPPORTUNITY',
        'characters': ['Leonel Graves'],
        'charactersOnCasesUid': '',
        'datetime': 'PLACEHOLDER',
        'description': "Upon examining the timeline and alibis, it is evident that Leonel Graves could not have had
the opportunity to commit the murder of Marisol Vega. On September 9th, 2023, the time of the murder has been
established through forensic evidence to be between 9:00 PM and 10:00 PM. Leonel Graves was hosting a large event
at the Convention Center, which is a 30-minute drive from the crime scene. The event was heavily attended, and
Leonel was actively engaged in his duties as an event planner, with multiple witnesses, including the event staff
and guests, confirming his presence from the start until the end of the event, which concluded at midnight.
Moreover, security camera footage from the Convention Center provides a visual confirmation of Leonel's presence
during the critical time frame. Therefore, given the distance, time constraints, and solid alibi, it is clear that
Leonel Graves could not have been at Marisol Vega's residence at the time of her murder.",
        'era': 0,
        'job': 'Leonel Graves truth opp',
        'name': 'Leonel Graves had no opportunity'
    },
    {
        'category': 'OPPORTUNITY',
        'characters': ['Rose Hawthorne'],
        'charactersOnCasesUid': '',
        'datetime': 'PLACEHOLDER',
        'description': "In the days leading up to September 9th, 2023, Dr. Rose Hawthorne's schedule was consistent
with her demanding role as a Cardiothoracic Surgeon. On the night of the murder, records and witness statements
corroborate that she was performing a complex surgery at the hospital. The surgery took place from 7 PM to 1 AM,
which coincides with the time frame of Marisol Vega's death. Her presence in the operating room is well-documented
and confirmed by her colleagues and the surgical team.",
        'era': -1,
        'job': 'Rose Hawthorne false_positive opp',
        'name': 'Rose Hawthorne maybe had opportunity'
    },
    {
        'category': 'OPPORTUNITY',
        'characters': ['Leonel Graves'],
        'charactersOnCasesUid': '',
        'datetime': 'PLACEHOLDER',
        'description': 'Leonel Graves was seen attending to his responsibilities at a large event at the Convention
Center in the days leading up to the murder of Marisol Vega. As an event planner, he was actively involved in the
coordination and execution of the event. Witnesses can confirm his presence at the venue, engaged in various tasks
related to his job. The Convention Center is located a significant distance from the crime scene, requiring a
30-minute drive to reach 1466 34th Ave, San Francisco. Security footage from the event venue corroborates the
witness statements, showing Graves at the Convention Center during the times in question.',
        'era': -1,
        'job': 'Leonel Graves false_positive opp',
        'name': 'Leonel Graves maybe had opportunity'
    },
    {
        'category': 'MEANS',
        'characters': ['Rose Hawthorne'],
        'charactersOnCasesUid': '',
        'datetime': 'PLACEHOLDER',
        'description': "Suspect Rose Hawthorne, a 28-year-old cardiothoracic surgeon, had the physical means to
commit the murder of Marisol Vega. As a medical professional, Hawthorne possessed the knowledge of human anatomy
and the physical strength required for the strangulation, consistent with the cause of death by high-tensile
strength nylon rope. Her medical expertise includes understanding of the human body's vulnerabilities, which could
be exploited to effectuate the act of strangling. Emotionally, Hawthorne's history of profound jealousy and
manipulative behavior towards the victim, stemming from their previous romantic relationship, establishes a motive.
The emotional toll from the relationship's end could have escalated into a violent confrontation. The combination
of her physical capabilities as a surgeon and her emotional state provides both the means and potential intent to
commit the murder.",
        'era': -4,
        'job': 'Rose Hawthorne truth means',
        'name': 'Rose Hawthorne had the means'
    },
    {
        'category': 'MEANS',
        'characters': ['Leonel Graves'],
        'charactersOnCasesUid': '',
        'datetime': 'PLACEHOLDER',
        'description': "Leonel Graves, aged 33, an event planner, had the physical and emotional means to commit
the murder of Marisol Vega. His job required the ability to carry heavy equipment and materials, indicating he had
the strength to handle the high-tensile strength nylon rope used in the murder. Graves's history with Vega included
a fall from grace within her social circle, leading to intense bitterness and resentment. These emotions could have
escalated into a motive for murder, providing the emotional means. The proximity of Graves to the victim, his
familiarity with her routines due to their past friendship, and his access to materials like the nylon rope through
his event planning resources all indicate that he had the means to commit the crime.",
        'era': -5,
        'job': 'Leonel Graves truth means',
        'name': 'Leonel Graves had the means'
    },
    {
        'category': 'MOTIVE',
        'characters': ['Rose Hawthorne', 'Marisol Vega'],
        'charactersOnCasesUid': '',
        'datetime': 'PLACEHOLDER',
        'description': "Leonel Graves, a former friend of Marisol Vega, was overheard arguing with her in a heated
exchange at a local bar. Witnesses report that Leonel accused Marisol of sabotaging his career by spreading rumors
within their shared professional network. The confrontation escalated when Leonel shouted that Marisol would regret
her actions. Friends of Marisol confirm that she had discovered unethical business practices by Leonel and had
shared her concerns with industry peers. This revelation damaged Leonel's reputation and led to the loss of
significant business opportunities. The argument ended with Leonel being escorted out by security, vowing that
Marisol would pay for her betrayal. The incident took place one month prior to Marisol's murder.",
        'era': -3,
        'job': 'Rose Hawthorne truth motive',
        'name': 'Rose Hawthorne had a motive'
    },
    {
        'category': 'MOTIVE',
        'characters': ['Leonel Graves', 'Marisol Vega'],
        'charactersOnCasesUid': '',
        'datetime': 'PLACEHOLDER',
        'description': "Marisol Vega and Leonel Graves engaged in a heated public argument at a charity event
organized by Marisol. Witnesses reported that the dispute centered around accusations from Marisol regarding
Leonel's mismanagement of event funds, which she claimed jeopardized the charity's reputation and mission. The
confrontation ended with Marisol vowing to expose Leonel's actions to the board of directors, potentially ruining
his career. This incident intensified Leonel's resentment towards Marisol, providing him with a motive for
murder.",
        'era': -3,
        'job': 'Leonel Graves truth motive',
        'name': 'Leonel Graves had a motive'
    }
]

# Run old events against the Marisol case

In [53]:
def generate_text(prompt: str, parameters={}):
  data = {"parameters": parameters, "prompt": prompt}
  print(f"Json: {data}")
  response = requests.post(f"{casescope_url}/openai/generate", json=data, headers=headers)
  data = response.json()
  return data

prompt = get_prompt(22)
marisol_old_events = generate_text(prompt, {
    "synopsis": marisol_synopsis,
    "charactersData": marisol_characters,
    "narrative": "" # ignore narrative for comparison evaluation of old and new event chains
    })
print(marisol_old_events)

[
    {
        'name': 'CASE_DETAILS',
        'description': 'Marisol Vega, a young woman thriving in her career as a Sustainable Design Consultant, was
found strangled to death at her San Francisco residence. Her sister, Juanita Vega, found her lifeless body and
notified the authorities.',
        'datetime': '2023-09-09T22:47:00Z',
        'category': 'EVENT',
        'era': 'BEGINNING',
        'charactersOnCasesUid': 'marisol-vega-case-0001'
    },
    {
        'name': 'ALTERCATION_AT_THE_BAR',
        'description': "Prior to the murder, Marisol had visited 'The Gilded Palace,' a bar where an altercation
escalated between Marisol and Alex Duran, the bartender on duty that night.",
        'datetime': '2023-09-09T20:00:00Z',
        'category': 'MOTIVE',
        'era': 'EVERY_DAY',
        'charactersOnCasesUid': 'marisol-vega-case-0002'
    },
    {
        'name': 'JEALOUSY_AMONG_CLOSE_CIRCLE',
        'description': "Long-standing tensions reached their climax in Marisol's close circles, involving personal
relationships tainted by jealousy, spite, and disillusionment.",
        'datetime': '2023-09-09T21:30:00Z',
        'category': 'MOTIVE',
        'era': 'ONE_DAY',
        'charactersOnCasesUid': 'marisol-vega-case-0003'
    },
    {
        'name': 'DURAN_FOLLOWS_MARISOL',
        'description': "After Marisol left 'The Gilded Palace', Alex Duran, unable to control his anger, followed
her home.",
        'datetime': '2023-09-09T22:00:00Z',
        'category': 'OPPORTUNITY',
        'era': 'CONSEQUENCE_1',
        'charactersOnCasesUid': 'marisol-vega-case-0002'
    },
    {
        'name': 'THE_MURDER',
        'description': 'Duran seized his opportunity to force himself into Vega’s residence and used a nylon rope
to strangle Marisol Vega.',
        'datetime': '2023-09-09T22:30:00Z',
        'category': 'MEANS',
        'era': 'CONSEQUENCE_2',
        'charactersOnCasesUid': 'marisol-vega-case-0002'
    },
    {
        'name': 'HAWTHORNE_OBSERVATION',
        'description': 'Meanwhile, Rose Hawthorne, Vega’s former romantic partner and a suspect, was observed near
the murder location.',
        'datetime': '2023-09-09T22:15:00Z',
        'category': 'OPPORTUNITY',
        'era': 'CONSEQUENCE_3',
        'charactersOnCasesUid': 'marisol-vega-case-0004'
    },
    {
        'name': 'JUANITA_DISCOVERS_MARISOL',
        'description': "Juanita Vega, Marisol's older sister, discovered Marisol’s lifeless body after coming home
from her date night.",
        'datetime': '2023-09-09T22:47:00Z',
        'category': 'EVENT',
        'era': 'FINALLY',
        'charactersOnCasesUid': 'marisol-vega-case-0005'
    },
    {
        'name': 'LAW_ENFORCMENT_ARRIVE',
        'description': "Following Juanita's distressed call, the police arrived at the crime scene.",
        'datetime': '2023-09-09T23:15:00Z',
        'category': 'EVENT',
        'era': 'THEN'
    },
    {
        'name': 'DURAN_SEEN_ON_CCTV',
        'description': "The police found CCTV footage of Alex Duran following Marisol from 'The Gilded Palace'.",
        'datetime': '2023-09-10T09:30:00Z',
        'category': 'MEANS',
        'era': 'THEN',
        'charactersOnCasesUid': 'marisol-vega-case-0002'
    },
    {
        'name': "ROPE_FOUND_ON_DURAN'S_PROPERTY",
        'description': "The police found the same type of rope used to strangle Marisol on Alex Duran's property
during their investigation.",
        'datetime': '2023-09-10T14:00:00Z',
        'category': 'MEANS',
        'era': 'THEN',
        'charactersOnCasesUid': 'marisol-vega-case-0002'
    },
    {
        'name': 'DURAN_ARRESTED',
        'description': 'Alex Duran was arrested by the police based on the collected evidence.',
        'datetime': '2023-09-10T16:30:00Z',
        'category': 'EVENT',
        'era': 'THEN',
        'charactersOnCasesUid': 'marisol-vega-case-0002'
    },
    {
        'name': 'DURAN_IN_COURT',
        'description': 'Alex Duran appeared in court for the first hearing after his arrest.',
        'datetime': '2023-09-11T10:00:00Z',
        'category': 'EVENT',
        'era': 'THEN',
        'charactersOnCasesUid': 'marisol-vega-case-0002'
    }
]

In [52]:
oldevents2timeline(marisol_old_events)


# BELOW IS OLD STUFF
---

# STEP 1 of 6: case_common_info / prompt no. 2

- step 2's case_synopsis depends on this step

In [ ]:
def generate_text(prompt: str, parameters={}):
  data = {"parameters": parameters, "prompt": prompt}
  print(f"Json: {data}")
  response = requests.post(f"{casescope_url}/openai/generate", json=data, headers=headers)
  data = response.json()
  return data

prompt = get_prompt(2)
case_common_info = generate_text(prompt)
# CaseMaker data format required for persisting data
print(case_common_info)

Prompt: You are a paralegal generating synthetic data for software training legal prosecutors. Create a new valid JSON describing a realistic police department fictional homicide case , crime type, cause of death, us based case location and number of suspects. Use less common causes of death. Avoid poisoning.

Your generations must be compatible with the style presented by the San Francisco District Attorney's Office. You present only facts. Use real-sounding fictional names, not placeholders like "John Doe". Limit all cases to the Bay Area. Keep dates in the range of 08/2022 to 09/2023.



Follow this format:

{

"caseName":""Case #123456 - Homicide - Gustavo Ruiz - 08/29/2023 - 100 Main St",

"crimeType":"Stabbing",

"caseLocation":"<<State, City, Police District>>",

"numberSuspects": <<integer in range from 3 to 7>>

}

Don't output markdown. Don't output three ticks. Just output pure JSON.
The JSON Object:
Json: {'parameters': {}, 'prompt': 'You are a paralegal generating synthetic data for software training legal prosecutors. Create a new valid JSON describing a realistic police department fictional homicide case , crime type, cause of death, us based case location and number of suspects. Use less common causes of death. Avoid poisoning.\n\nYour generations must be compatible with the style presented by the San Francisco District Attorney\'s Office. You present only facts. Use real-sounding fictional names, not placeholders like "John Doe". Limit all cases to the Bay Area. Keep dates in the range of 08/2022 to 09/2023.\n\n\n\nFollow this format: \n\n{ \n\n"caseName":""Case #123456 - Homicide - Gustavo Ruiz - 08/29/2023 - 100 Main St", \n\n"crimeType":"Stabbing", \n\n"caseLocation":"<<State, City, Police District>>", \n\n"numberSuspects": <<integer in range from 3 to 7>>\n\n}\n\nDon\'t output markdown. Don\'t output three ticks. Just output pure JSON. \nThe JSON Object:'}
{'caseName': 'Case #987654 - Homicide - Amanda Wilkins - 09/15/2023 - 543 Elm St', 'crimeType': 'Strangulation', 'caseLocation': 'California, San Jose, Southside District', 'numberSuspects': 4}

# STEP 2 of 6: case_synopsis / prompt 3

- depends on step 1's output `case_common_info`

In [ ]:
prompt = get_prompt(3)
case_synopsis = generate_text(prompt, {"case_name": case_common_info["caseName"], "crime_type": case_common_info["crimeType"], "crime_location": case_common_info["caseLocation"], "suspects_number": case_common_info["numberSuspects"]})
# CaseMaker data format required for persisting data
print(case_synopsis)

Prompt: You are a wikipedia editor summarizing crime cases. Your descriptions have an object,  omniscient point of view, and know every fact and thought in every participants mind.

Your generations must be compatible with the style presented by the San Francisco Police Department. You present only facts. Use real-sounding fictional names, not placeholders like "John Doe". Limit all cases to the Bay Area. Keep dates in the range of 08/2022 to 09/2023. Create a new valid synopsis describing a realistic police department fictional homicide case.


Given these case details:

"caseName":"{{case_name}}",

"crimeType":"{{crime_type}}",

"caseLocation":"{{crime_location}}",

"numberSuspects": {{suspects_number}}



to the following template for a legal case indictment. all descriptions must be totally omniscient. If no details exist in the prompt, generate them. Be completely factual in your depiction, conveying only falsifiable facts, adopting the tone of a wikipedia article.

### Synopsis
A bullet point overview of the case

### Characters

- Create the victim of the murder and write a 1-2 sentence description. include REALISTIC INCLUSIVE FIRST NAME, REALISTIC INCLUSIVE UNCOMMON LAST NAME, REALISTIC NAICS OCCUPATION NAME (no code)
- Create three suspects and write a 1-2 sentence description. One is the killer, the others are red herrings.
    1. Suspect_1
    2. Suspect_2
    3. Suspect_3
- Create a witness to the murder and write a 1-2 sentence description.

### **Means, Motive & Opportunity**

- **Means:** The method in which the victim was killed. Generate the murder weapon. Must included specific description of the weapon or implement. Include product name and SKU.
- **Motive:** Write 2-3 ulterior motives for each suspect. Motives can include personality traits, vendettas against the victim, or relationships between the victim and the suspects.
    - Suspect_1:
    - Suspect_2:
    - Suspect_3:
- **Opportunity:** Write 1-2 sentences for each suspect that places them at the scene of the murder or with the victim prior to the murder.
    - Suspect_1:
    - Suspect_2:
    - Suspect_3:


### The Night Of

- Write 3-4 paragraphs that describe what happened the night of the murder. This section should include the name of the murderer, how they committed the murder, and why they committed the murder.
Json: {'parameters': {'case_name': 'Case #987654 - Homicide - Amanda Wilkins - 09/15/2023 - 543 Elm St', 'crime_type': 'Strangulation', 'crime_location': 'California, San Jose, Southside District', 'suspects_number': 4}, 'prompt': 'You are a wikipedia editor summarizing crime cases. Your descriptions have an object,  omniscient point of view, and know every fact and thought in every participants mind. \n\nYour generations must be compatible with the style presented by the San Francisco Police Department. You present only facts. Use real-sounding fictional names, not placeholders like "John Doe". Limit all cases to the Bay Area. Keep dates in the range of 08/2022 to 09/2023. Create a new valid synopsis describing a realistic police department fictional homicide case.\n\n\nGiven these case details:\n\n"caseName":"{{case_name}}",\n\n"crimeType":"{{crime_type}}",\n\n"caseLocation":"{{crime_location}}",\n\n"numberSuspects": {{suspects_number}}\n\n\n\nto the following template for a legal case indictment. all descriptions must be totally omniscient. If no details exist in the prompt, generate them. Be completely factual in your depiction, conveying only falsifiable facts, adopting the tone of a wikipedia article.\n\n### Synopsis\nA bullet point overview of the case\n\n### Characters\n\n- Create the victim of the murder and write a 1-2 sentence description. include REALISTIC INCLUSIVE FIRST NAME, REALISTIC INCLUSIVE UNCOMMON LAST NAME, REALISTIC NAICS OCCUPATION NAME (no code)\n- Create three suspects and write a 1-2 sentence description. One is the killer, the others are red herrings.\n    1. Suspect_1\n    2. Suspect_2\n    3. Suspect_3\n- Create a witness to the murder and write a 1-2 sentence description.\n\n### **Means, Motive & Opportunity**\n\n- **Means:** The method in which the victim was killed. Generate the murder weapon. Must included specific description of the weapon or implement. Include product name and SKU.\n- **Motive:** Write 2-3 ulterior motives for each suspect. Motives can include personality traits, vendettas against the victim, or relationships between the victim and the suspects.\n    - Suspect_1:\n    - Suspect_2:\n    - Suspect_3:\n- **Opportunity:** Write 1-2 sentences for each suspect that places them at the scene of the murder or with the victim prior to the murder.\n    - Suspect_1:\n    - Suspect_2:\n    - Suspect_3:\n\n\n### The Night Of\n\n- Write 3-4 paragraphs that describe what happened the night of the murder. This section should include the name of the murderer, how they committed the murder, and why they committed the murder.'}
### Synopsis
On the evening of September 15, 2023, Amanda Wilkins was found deceased in her residence on 543 Elm Street, Southside District, San Jose, California. The primary cause of death was ruled as strangulation. Four suspects were identified in connection with this case, involving a complex web of strained relationships, financial motivations, and potential vendettas against the victim.

### Characters
- **Victim: Amanda Wilkins**, an Environmental Engineering Technician, found dead in her home.
- **Suspect 1: Ernesto Ramirez**, a maintenance worker at the building where Wilkins resided. Known for his aggressive and confrontational personality.
- **Suspect 2: Maria Abery**, Wilkins' ex-partner. They had a tumultuous breakup with several public altercations in the past.
- **Suspect 3: Gary Schultz**, a stock market investor facing bankruptcy. Recently, Wilkins had accused him of defrauding her of significant savings.
- **Witness: Lucy Finch**, neighbor to Wilkins and a reclusive blogger. Lucy reported hearing loud noises coming from Wilkins' apartment on the night of the murder.

### Means, Motive & Opportunity

- **Means:** The victim was killed by strangulation using a 47-inch Black Diamond ATC Belay Device with product SKU BD6200750000ALL1, typically used in rock climbing, which Amanda Wilkins was known to enjoy.

- **Motive:**
    - **Ernesto Ramirez**: Ramirez and Wilkins had a tense working relationship; he was responsible for numerous unresolved maintenance complaints lodged by Wilkins and bore a grudge against her.
    - **Maria Abery**: Abery was engaged in an ongoing custody battle for their shared pet dog, Huckleberry. Plus, she disapproved of Wilkins' new romantic relationship.
    - **Gary Schultz**: Schultz was accused of depleting Wilkins' savings in bad investments, and Wilkins' threat of legal action could have led to his imprisonment.

- **Opportunity:**
    - **Ernesto Ramirez**: Ramirez had unrestricted access to the entire apartment building, including the victim's unit.
    - **Maria Abery**: Abery had been seen in the area earlier in the evening, as reported by multiple sources.
    - **Gary Schultz**: Schultz had attended a group meeting in a restaurant opposite Wilkins' apartment on the night of the murder.

### The Night Of

On the night of September 15, 2023, Amanda Wilkins was seen arriving home from work at her usual time. Sometime later, Lucy Finch reported hearing "thumping noises". At the same time, Ernesto Ramirez was finishing his shift, Gary Schultz was having volatile discussions at a nearby restaurant, and Maria Abery was also in the vicinity. It was a setting destined to end in tragedy.

Maria Abery, hoping to reconcile with Wilkins before the dog custody hearing, had arrived at the apartment complex, but was dissuaded by seeing Gary Schultz already present. Ernesto Ramirez, having heard of Schultz's presence from the building's doorman, took the opportunity to settle a long-standing grudge against the victim. Ramirez used a climbing gear, which he found in Wilkins' apartment, to murder her.

Ramirez had felt gravely aggrieved by Wilkins' persistent complaints about maintenance issues, feeling disrespected by it. The sight of Schultz - whom he didn't know - arriving at the building while Ramirez was still nursing his anger somehow escalated his feelings to a fatal degree. After ensuring no one was around, he sneaked into Wilkins' apartment and committed the crime, leaving the same way he got in.

In [ ]:
print(case_synopsis)

### Synopsis
On the evening of September 15, 2023, Amanda Wilkins was found deceased in her residence on 543 Elm Street, Southside District, San Jose, California. The primary cause of death was ruled as strangulation. Four suspects were identified in connection with this case, involving a complex web of strained relationships, financial motivations, and potential vendettas against the victim.

### Characters
- **Victim: Amanda Wilkins**, an Environmental Engineering Technician, found dead in her home.
- **Suspect 1: Ernesto Ramirez**, a maintenance worker at the building where Wilkins resided. Known for his aggressive and confrontational personality.
- **Suspect 2: Maria Abery**, Wilkins' ex-partner. They had a tumultuous breakup with several public altercations in the past.
- **Suspect 3: Gary Schultz**, a stock market investor facing bankruptcy. Recently, Wilkins had accused him of defrauding her of significant savings.
- **Witness: Lucy Finch**, neighbor to Wilkins and a reclusive blogger. Lucy reported hearing loud noises coming from Wilkins' apartment on the night of the murder.

### Means, Motive & Opportunity

- **Means:** The victim was killed by strangulation using a 47-inch Black Diamond ATC Belay Device with product SKU BD6200750000ALL1, typically used in rock climbing, which Amanda Wilkins was known to enjoy.

- **Motive:**
    - **Ernesto Ramirez**: Ramirez and Wilkins had a tense working relationship; he was responsible for numerous unresolved maintenance complaints lodged by Wilkins and bore a grudge against her.
    - **Maria Abery**: Abery was engaged in an ongoing custody battle for their shared pet dog, Huckleberry. Plus, she disapproved of Wilkins' new romantic relationship.
    - **Gary Schultz**: Schultz was accused of depleting Wilkins' savings in bad investments, and Wilkins' threat of legal action could have led to his imprisonment.

- **Opportunity:**
    - **Ernesto Ramirez**: Ramirez had unrestricted access to the entire apartment building, including the victim's unit.
    - **Maria Abery**: Abery had been seen in the area earlier in the evening, as reported by multiple sources.
    - **Gary Schultz**: Schultz had attended a group meeting in a restaurant opposite Wilkins' apartment on the night of the murder.

### The Night Of

On the night of September 15, 2023, Amanda Wilkins was seen arriving home from work at her usual time. Sometime later, Lucy Finch reported hearing "thumping noises". At the same time, Ernesto Ramirez was finishing his shift, Gary Schultz was having volatile discussions at a nearby restaurant, and Maria Abery was also in the vicinity. It was a setting destined to end in tragedy.

Maria Abery, hoping to reconcile with Wilkins before the dog custody hearing, had arrived at the apartment complex, but was dissuaded by seeing Gary Schultz already present. Ernesto Ramirez, having heard of Schultz's presence from the building's doorman, took the opportunity to settle a long-standing grudge against the victim. Ramirez used a climbing gear, which he found in Wilkins' apartment, to murder her.

Ramirez had felt gravely aggrieved by Wilkins' persistent complaints about maintenance issues, feeling disrespected by it. The sight of Schultz - whom he didn't know - arriving at the building while Ramirez was still nursing his anger somehow escalated his feelings to a fatal degree. After ensuring no one was around, he sneaked into Wilkins' apartment and committed the crime, leaving the same way he got in.

# `case_intro` IRRELEVENT

In [ ]:
prompt = get_prompt(4)
case_intro = generate_text(prompt, {"case_name": case_common_info["caseName"], "crime_type": case_common_info["crimeType"], "crime_location": case_common_info["caseLocation"], "suspects_number": case_common_info["numberSuspects"], "synopsis": case_synopsis})
# CaseMaker data format required for persisting data
print(case_intro)

Prompt: You are a paralegal generating synthetic data for software training legal prosecutors. You have JSON of the crime case described as this:
{
"caseName":"{{case_name}}",
"crimeType":"{{crime_type}}",
"caseLocation":"{{crime_location}}",
"numberSuspects": {{suspects_number}},
"synopsis": {{synopsis}}
}

Create user's introduction to the case in the serious, realistic tone of a bulletin issued by the police department for their computer screens, avoiding unnecessary jargon, using Zinsser guidelines for directness and succinctness, example "Attention all units, we have a new case on our hands. Case Name: {{case_name}}. The case involves a serious incident of {{crime_type}}. The crime took place at {{crime_location}}. We have {{suspects_number}} suspects on our radar so far. Stay alert and proceed with caution. Let's bring justice swiftly and efficiently." The intro begins:
Json: {'parameters': {'case_name': 'Case #987654 - Homicide - Amanda Wilkins - 09/15/2023 - 543 Elm St', 'crime_type': 'Strangulation', 'crime_location': 'California, San Jose, Southside District', 'suspects_number': 4, 'synopsis': '### Synopsis\nOn the evening of September 15, 2023, Amanda Wilkins was found deceased in her residence on 543 Elm Street, Southside District, San Jose, California. The primary cause of death was ruled as strangulation. Four suspects were identified in connection with this case, involving a complex web of strained relationships, financial motivations, and potential vendettas against the victim.\n\n### Characters\n- **Victim: Amanda Wilkins**, an Environmental Engineering Technician, found dead in her home.\n- **Suspect 1: Ernesto Ramirez**, a maintenance worker at the building where Wilkins resided. Known for his aggressive and confrontational personality.\n- **Suspect 2: Maria Abery**, Wilkins\' ex-partner. They had a tumultuous breakup with several public altercations in the past.\n- **Suspect 3: Gary Schultz**, a stock market investor facing bankruptcy. Recently, Wilkins had accused him of defrauding her of significant savings.\n- **Witness: Lucy Finch**, neighbor to Wilkins and a reclusive blogger. Lucy reported hearing loud noises coming from Wilkins\' apartment on the night of the murder.\n\n### Means, Motive & Opportunity\n\n- **Means:** The victim was killed by strangulation using a 47-inch Black Diamond ATC Belay Device with product SKU BD6200750000ALL1, typically used in rock climbing, which Amanda Wilkins was known to enjoy.\n  \n- **Motive:**\n    - **Ernesto Ramirez**: Ramirez and Wilkins had a tense working relationship; he was responsible for numerous unresolved maintenance complaints lodged by Wilkins and bore a grudge against her.\n    - **Maria Abery**: Abery was engaged in an ongoing custody battle for their shared pet dog, Huckleberry. Plus, she disapproved of Wilkins\' new romantic relationship.\n    - **Gary Schultz**: Schultz was accused of depleting Wilkins\' savings in bad investments, and Wilkins\' threat of legal action could have led to his imprisonment.\n  \n- **Opportunity:**\n    - **Ernesto Ramirez**: Ramirez had unrestricted access to the entire apartment building, including the victim\'s unit.\n    - **Maria Abery**: Abery had been seen in the area earlier in the evening, as reported by multiple sources.\n    - **Gary Schultz**: Schultz had attended a group meeting in a restaurant opposite Wilkins\' apartment on the night of the murder.\n\n### The Night Of\n\nOn the night of September 15, 2023, Amanda Wilkins was seen arriving home from work at her usual time. Sometime later, Lucy Finch reported hearing "thumping noises". At the same time, Ernesto Ramirez was finishing his shift, Gary Schultz was having volatile discussions at a nearby restaurant, and Maria Abery was also in the vicinity. It was a setting destined to end in tragedy.\n\nMaria Abery, hoping to reconcile with Wilkins before the dog custody hearing, had arrived at the apartment complex, but was dissuaded by seeing Gary Schultz already present. Ernesto Ramirez, having heard of Schultz\'s presence from the building\'s doorman, took the opportunity to settle a long-standing grudge against the victim. Ramirez used a climbing gear, which he found in Wilkins\' apartment, to murder her.\n\nRamirez had felt gravely aggrieved by Wilkins\' persistent complaints about maintenance issues, feeling disrespected by it. The sight of Schultz - whom he didn\'t know - arriving at the building while Ramirez was still nursing his anger somehow escalated his feelings to a fatal degree. After ensuring no one was around, he sneaked into Wilkins\' apartment and committed the crime, leaving the same way he got in.'}, 'prompt': 'You are a paralegal generating synthetic data for software training legal prosecutors. You have JSON of the crime case described as this:\n{\n"caseName":"{{case_name}}",\n"crimeType":"{{crime_type}}",\n"caseLocation":"{{crime_location}}",\n"numberSuspects": {{suspects_number}},\n"synopsis": {{synopsis}}\n}\n\nCreate user\'s introduction to the case in the serious, realistic tone of a bulletin issued by the police department for their computer screens, avoiding unnecessary jargon, using Zinsser guidelines for directness and succinctness, example "Attention all units, we have a new case on our hands. Case Name: {{case_name}}. The case involves a serious incident of {{crime_type}}. The crime took place at {{crime_location}}. We have {{suspects_number}} suspects on our radar so far. Stay alert and proceed with caution. Let\'s bring justice swiftly and efficiently." The intro begins:'}
Attention officers, we've got a new homicide on our hands. Case #987654 pertains to the tragic death of Amanda Wilkins that took place on September 15, 2023, at 543 Elm St in the Southside District of San Jose, California. Our victim suffered a lethal strangulation, with the primary weapon identified as a specialized rock climbing gear. Currently, four suspects are under investigation involved in a complicated web of personal and financial gripes against Wilkins. Discretion, alertness, and due diligence are of utmost importance in this case. Let's operate swiftly, assuredly, and ensure that justice prevails for Amanda Wilkins.

# STEP 3 of 6: `case_synopsis_md` / prompt 25

In [ ]:
prompt = get_prompt(25)
case_synopsis_md = generate_text(prompt, {"synopsis": case_synopsis})
# CaseMaker data format required for persisting data
md(case_synopsis_md)

Prompt: You are a paralegal creating software for writing indictments. Your sample cases have an omniscient point of view, and know every fact and thought in every participants mind. convert the following synopsis:
{{synopsis}}

to the following template for a legal case indictment. all descriptions must be totally omniscient. If no details exist in the prompt, generate them.

### Synopsis

- Two paragraphs that provide the following information:
    - Name of the victim(s) and cause of death.
    - Date and time the murder took place.
    - Name of the person who notified police along with the time the call was made.
    - Any significant moment or event that predicated the murder.

### Characters

- Create the victim of the murder and write a 1-2 sentence description. include REALISTIC INCLUSIVE FIRST NAME, REALISTIC INCLUSIVE UNCOMMON LAST NAME, REALISTIC NAICS OCCUPATION
- Create three suspects and write a 1-2 sentence description. One is the killer, the others are red herrings.
    1. Suspect_1
    2. Suspect_2
    3. Suspect_3
- Create a witness to the murder and write a 1-2 sentence description.

### **Means, Motive & Opportunity**

- **Means:** The method in which the victim was killed. Generate the murder weapon. Must included specific description of the weapon or implement. Include product name and SKU.
- **Motive:** Write 2-3 ulterior motives for each suspect. Motives can include personality traits, vendettas against the victim, or relationships between the victim and the suspects.
    - Suspect_1:
    - Suspect_2:
    - Suspect_3:
- **Opportunity:** Write 1-2 sentences for each suspect that places them at the scene of the murder or with the victim prior to the murder.
    - Suspect_1:
    - Suspect_2:
    - Suspect_3:


### The Night Of

- Write 3-4 paragraphs that describe what happened the night of the murder. This section should include the name of the murderer, how they committed the murder, and why they committed the murder.

Json: {'parameters': {'synopsis': '### Synopsis\nOn the evening of September 15, 2023, Amanda Wilkins was found deceased in her residence on 543 Elm Street, Southside District, San Jose, California. The primary cause of death was ruled as strangulation. Four suspects were identified in connection with this case, involving a complex web of strained relationships, financial motivations, and potential vendettas against the victim.\n\n### Characters\n- **Victim: Amanda Wilkins**, an Environmental Engineering Technician, found dead in her home.\n- **Suspect 1: Ernesto Ramirez**, a maintenance worker at the building where Wilkins resided. Known for his aggressive and confrontational personality.\n- **Suspect 2: Maria Abery**, Wilkins\' ex-partner. They had a tumultuous breakup with several public altercations in the past.\n- **Suspect 3: Gary Schultz**, a stock market investor facing bankruptcy. Recently, Wilkins had accused him of defrauding her of significant savings.\n- **Witness: Lucy Finch**, neighbor to Wilkins and a reclusive blogger. Lucy reported hearing loud noises coming from Wilkins\' apartment on the night of the murder.\n\n### Means, Motive & Opportunity\n\n- **Means:** The victim was killed by strangulation using a 47-inch Black Diamond ATC Belay Device with product SKU BD6200750000ALL1, typically used in rock climbing, which Amanda Wilkins was known to enjoy.\n  \n- **Motive:**\n    - **Ernesto Ramirez**: Ramirez and Wilkins had a tense working relationship; he was responsible for numerous unresolved maintenance complaints lodged by Wilkins and bore a grudge against her.\n    - **Maria Abery**: Abery was engaged in an ongoing custody battle for their shared pet dog, Huckleberry. Plus, she disapproved of Wilkins\' new romantic relationship.\n    - **Gary Schultz**: Schultz was accused of depleting Wilkins\' savings in bad investments, and Wilkins\' threat of legal action could have led to his imprisonment.\n  \n- **Opportunity:**\n    - **Ernesto Ramirez**: Ramirez had unrestricted access to the entire apartment building, including the victim\'s unit.\n    - **Maria Abery**: Abery had been seen in the area earlier in the evening, as reported by multiple sources.\n    - **Gary Schultz**: Schultz had attended a group meeting in a restaurant opposite Wilkins\' apartment on the night of the murder.\n\n### The Night Of\n\nOn the night of September 15, 2023, Amanda Wilkins was seen arriving home from work at her usual time. Sometime later, Lucy Finch reported hearing "thumping noises". At the same time, Ernesto Ramirez was finishing his shift, Gary Schultz was having volatile discussions at a nearby restaurant, and Maria Abery was also in the vicinity. It was a setting destined to end in tragedy.\n\nMaria Abery, hoping to reconcile with Wilkins before the dog custody hearing, had arrived at the apartment complex, but was dissuaded by seeing Gary Schultz already present. Ernesto Ramirez, having heard of Schultz\'s presence from the building\'s doorman, took the opportunity to settle a long-standing grudge against the victim. Ramirez used a climbing gear, which he found in Wilkins\' apartment, to murder her.\n\nRamirez had felt gravely aggrieved by Wilkins\' persistent complaints about maintenance issues, feeling disrespected by it. The sight of Schultz - whom he didn\'t know - arriving at the building while Ramirez was still nursing his anger somehow escalated his feelings to a fatal degree. After ensuring no one was around, he sneaked into Wilkins\' apartment and committed the crime, leaving the same way he got in.'}, 'prompt': 'You are a paralegal creating software for writing indictments. Your sample cases have an omniscient point of view, and know every fact and thought in every participants mind. convert the following synopsis:\n{{synopsis}}\n\nto the following template for a legal case indictment. all descriptions must be totally omniscient. If no details exist in the prompt, generate them.\n\n### Synopsis\n\n- Two paragraphs that provide the following information:\n    - Name of the victim(s) and cause of death.\n    - Date and time the murder took place.\n    - Name of the person who notified police along with the time the call was made.\n    - Any significant moment or event that predicated the murder.\n\n### Characters\n\n- Create the victim of the murder and write a 1-2 sentence description. include REALISTIC INCLUSIVE FIRST NAME, REALISTIC INCLUSIVE UNCOMMON LAST NAME, REALISTIC NAICS OCCUPATION\n- Create three suspects and write a 1-2 sentence description. One is the killer, the others are red herrings.\n    1. Suspect_1\n    2. Suspect_2\n    3. Suspect_3\n- Create a witness to the murder and write a 1-2 sentence description.\n\n### **Means, Motive & Opportunity**\n\n- **Means:** The method in which the victim was killed. Generate the murder weapon. Must included specific description of the weapon or implement. Include product name and SKU.\n- **Motive:** Write 2-3 ulterior motives for each suspect. Motives can include personality traits, vendettas against the victim, or relationships between the victim and the suspects.\n    - Suspect_1:\n    - Suspect_2:\n    - Suspect_3:\n- **Opportunity:** Write 1-2 sentences for each suspect that places them at the scene of the murder or with the victim prior to the murder.\n    - Suspect_1:\n    - Suspect_2:\n    - Suspect_3:\n\n\n### The Night Of\n\n- Write 3-4 paragraphs that describe what happened the night of the murder. This section should include the name of the murderer, how they committed the murder, and why they committed the murder.\n'}

### Synopsis

In the quiet town of Southside District, San Jose, California, peace was disrupted when the lifeless body of a local resident, Amanda Wilkins, was discovered in her residence at 543 Elm Street at 11:45 pm on September 15, 2023. The autopsy report showed that the cause of Amanda Wilkin's death was strangulation. Alarmed by the disturbing sounds she'd heard earlier that night, Lucy Finch, a recluse and neighbor to the victim, alerted the local police at 12:34 am on September 16.

Tensions had been rising between Wilkins and a few individuals in the area due to a mixture of personal disputes, financial disagreements, and potential grudges. This made the unfolding crime scene tainted with strained emotions and potential motives, perfectly set for a sinister murder-mystery.

### Characters

- **Victim: Amanda Wilkins**, an Environmental Engineering Technician, whose life was abruptly taken in the sanctuary of her own home.
- **Suspect 1: Ernesto Ramirez**, a building maintenance worker whose abrasive personality often put him at odds with the residents, especially Amanda Wilkins.
- **Suspect 2: Maria Abery**, a Visual Arts Consultant and Wilkins' ex-partner, known for their public disagreements following their dramatic breakup.
- **Suspect 3: Gary Schultz**, a distressed Stock Marker Investor who was recently accused of swindling considerable savings from Wilkins.
- **Witness: Lucy Finch**, a relatively isolationist blogger who lived next door to the victim and alerted authorities after hearing disturbing noises from Wilkins' home.

### Means, Motive & Opportunity

- **Means:** Strangulation was the determined cause of death, specifically executed with a 47-inch Black Diamond ATC Belay Device, product SKU BD6200750000ALL1, commonly used in rock climbing.

- **Motive:**
    - **Ernesto Ramirez**: Ramirez harbored resentment for the victim stemming from her persistent maintenance complaints coupled with his perception of being disrespected.
    - **Maria Abery**: Devastated by their failed relationship, Abery was locked in a bitter custody dispute over a shared pet, not to mention her disdain for Wilkins' new romantic interest.
    - **Gary Schultz**: Schultz was under pressure as he faced accusations for defrauding Wilkins of a large sum of her savings and the looming threat of legal action from Wilkins could mean jail time.

- **Opportunity:**
    - **Ernesto Ramirez**: As the apartment building's maintenance worker, Ramirez had unrestricted access to all the residential units.
    - **Maria Abery**: Multiple sources reported seeing Abery in close proximity to the apartment complex on the evening of the homicide.
    - **Gary Schultz**: Schultz was observed attending a meeting in a restaurant directly opposite Wilkins' residence the night the crime occurred.

### The Night Of

The fatal night of September 15, 2023, appeared to start as any other evening for Amanda Wilkins as she returned from work, but before the night was over, her life would be cruelly snatched away. The neighborhood held its breath as the usual suspects emerged, each with their motive and opportunity. Ernesto Ramirez just finished his shift at the apartment building as he nursed a growing resentment for Wilkins. While Maria Abery, hoping to salvage any remaining warmth from their relationship before a legal decision severed their shared custody of Huckleberry, was close by. Gary Schultz, burdened by financial woes and potential fraud charges from Wilkins, was engaged in a heated discussion at a nearby restaurant.

Fate, though, determined that Ernesto Ramirez would be the orchestrator of the fatal ending. Witnessing Gary in the area from the building's doorman, a spike of anger drove him to seize the moment to settle his grievance against Wilkins. Infiltrating her residence, Ramirez found Wilkins' climbing gear - a 47-inch Black Diamond ATC Belay Device - and used it as the instrument of his wrath.

Ramirez, feeling repeatedly slighted by Wilkins' incessant maintenance complaints and viewing himself as the unjust target of disrespect, was consumed by rage. The appearance of Schultz, a stranger to Ramirez but known adversary to Wilkins, incensed his anger to murderous intent. Assuring himself the coast was clear, he snuck into Wilkin's apartment, executed his fatal act, and slipped away into the night.

# Step 4 of 6 /prompt 28 `case_narrative`

In [ ]:
prompt = get_prompt(28)
case_narrative = generate_text(prompt, { "case_synopsis_md": case_synopsis_md, })
# CaseMaker data format required for persisting data
pp.pprint(case_narrative)

Prompt: You are a simulated reporter working the crime beat. You are writing stories that capture all of the key details of a crime. Your work is used in software to train paralegals and is not tied to real events.

Your generations must be compatible with the style presented by the San Francisco Chronicle. You present only facts. Use real-sounding fictional names, not placeholders like "John Doe". Limit all cases to the Bay Area. Keep dates in the range of 08/2022 to 09/2023. Create a new valid synopsis describing a realistic police department fictional homicide case.

Given case details described in this synopsis:

{{case_synopsis_md}}

Generate a detailed narrative describing events that happened in the style of a newspaper reporter on a common crime story.
Narrative might describe what happened in the past or way in the future relative to investigation.
Narrative has to include all the facts of the case including the solution.
Style the narrative description as a series of events descriptions but provide it in a form of interconnected story.
Include plausible connections for the alternate suspects that make them look like they could be the culprit, but aren't.
Make sure that person who's familiar with all the events will be able to point to the case solution.


Your narrative style must be compact, factual, and to the point. Do not waste a single word on emotional content. Use Zinsser style grammar and syntax.

return only narrative string. do not return any instructions or explanation.
Json: {'parameters': {'case_synopsis_md': "### Synopsis\n\nIn the quiet town of Southside District, San Jose, California, peace was disrupted when the lifeless body of a local resident, Amanda Wilkins, was discovered in her residence at 543 Elm Street at 11:45 pm on September 15, 2023. The autopsy report showed that the cause of Amanda Wilkin's death was strangulation. Alarmed by the disturbing sounds she'd heard earlier that night, Lucy Finch, a recluse and neighbor to the victim, alerted the local police at 12:34 am on September 16.\n\nTensions had been rising between Wilkins and a few individuals in the area due to a mixture of personal disputes, financial disagreements, and potential grudges. This made the unfolding crime scene tainted with strained emotions and potential motives, perfectly set for a sinister murder-mystery.\n\n### Characters\n\n- **Victim: Amanda Wilkins**, an Environmental Engineering Technician, whose life was abruptly taken in the sanctuary of her own home.\n- **Suspect 1: Ernesto Ramirez**, a building maintenance worker whose abrasive personality often put him at odds with the residents, especially Amanda Wilkins.\n- **Suspect 2: Maria Abery**, a Visual Arts Consultant and Wilkins' ex-partner, known for their public disagreements following their dramatic breakup.\n- **Suspect 3: Gary Schultz**, a distressed Stock Marker Investor who was recently accused of swindling considerable savings from Wilkins.\n- **Witness: Lucy Finch**, a relatively isolationist blogger who lived next door to the victim and alerted authorities after hearing disturbing noises from Wilkins' home.\n\n### Means, Motive & Opportunity\n\n- **Means:** Strangulation was the determined cause of death, specifically executed with a 47-inch Black Diamond ATC Belay Device, product SKU BD6200750000ALL1, commonly used in rock climbing.\n\n- **Motive:**\n    - **Ernesto Ramirez**: Ramirez harbored resentment for the victim stemming from her persistent maintenance complaints coupled with his perception of being disrespected.\n    - **Maria Abery**: Devastated by their failed relationship, Abery was locked in a bitter custody dispute over a shared pet, not to mention her disdain for Wilkins' new romantic interest.\n    - **Gary Schultz**: Schultz was under pressure as he faced accusations for defrauding Wilkins of a large sum of her savings and the looming threat of legal action from Wilkins could mean jail time.\n  \n- **Opportunity:**\n    - **Ernesto Ramirez**: As the apartment building's maintenance worker, Ramirez had unrestricted access to all the residential units.\n    - **Maria Abery**: Multiple sources reported seeing Abery in close proximity to the apartment complex on the evening of the homicide.\n    - **Gary Schultz**: Schultz was observed attending a meeting in a restaurant directly opposite Wilkins' residence the night the crime occurred.\n\n### The Night Of\n\nThe fatal night of September 15, 2023, appeared to start as any other evening for Amanda Wilkins as she returned from work, but before the night was over, her life would be cruelly snatched away. The neighborhood held its breath as the usual suspects emerged, each with their motive and opportunity. Ernesto Ramirez just finished his shift at the apartment building as he nursed a growing resentment for Wilkins. While Maria Abery, hoping to salvage any remaining warmth from their relationship before a legal decision severed their shared custody of Huckleberry, was close by. Gary Schultz, burdened by financial woes and potential fraud charges from Wilkins, was engaged in a heated discussion at a nearby restaurant.\n\nFate, though, determined that Ernesto Ramirez would be the orchestrator of the fatal ending. Witnessing Gary in the area from the building's doorman, a spike of anger drove him to seize the moment to settle his grievance against Wilkins. Infiltrating her residence, Ramirez found Wilkins' climbing gear - a 47-inch Black Diamond ATC Belay Device - and used it as the instrument of his wrath. \n\nRamirez, feeling repeatedly slighted by Wilkins' incessant maintenance complaints and viewing himself as the unjust target of disrespect, was consumed by rage. The appearance of Schultz, a stranger to Ramirez but known adversary to Wilkins, incensed his anger to murderous intent. Assuring himself the coast was clear, he snuck into Wilkin's apartment, executed his fatal act, and slipped away into the night.\n"}, 'prompt': 'You are a simulated reporter working the crime beat. You are writing stories that capture all of the key details of a crime. Your work is used in software to train paralegals and is not tied to real events.\n\nYour generations must be compatible with the style presented by the San Francisco Chronicle. You present only facts. Use real-sounding fictional names, not placeholders like "John Doe". Limit all cases to the Bay Area. Keep dates in the range of 08/2022 to 09/2023. Create a new valid synopsis describing a realistic police department fictional homicide case.\n\nGiven case details described in this synopsis:\n\n{{case_synopsis_md}}\n\nGenerate a detailed narrative describing events that happened in the style of a newspaper reporter on a common crime story.\nNarrative might describe what happened in the past or way in the future relative to investigation.\nNarrative has to include all the facts of the case including the solution.\nStyle the narrative description as a series of events descriptions but provide it in a form of interconnected story.\nInclude plausible connections for the alternate suspects that make them look like they could be the culprit, but aren\'t.\nMake sure that person who\'s familiar with all the events will be able to point to the case solution.\n\n\nYour narrative style must be compact, factual, and to the point. Do not waste a single word on emotional content. Use Zinsser style grammar and syntax.\n\nreturn only narrative string. do not return any instructions or explanation.'}
('In the serene confines of Southside District, San Jose, tranquility '
 'shattered on September 15, 2023. The lifeless body of Amanda Wilkins, a '
 'local Environmental Engineering Technician, was found at her residence at '
 '543 Elm Street at 11:45 pm. Lucy Finch, a hermit-like blogger living '
 'adjacent to Wilkins, alerted cops around 12:34 am on September 16, spurred '
 'by unusual noises she heard.\n'
 '\n'
 'An autopsy determined the cause of death as strangulation, executed with a '
 '47-inch Black Diamond ATC Belay Device, SKU BD6200750000ALL1, typically used '
 'in rock climbing. The convoluted web of relationships around Wilkins served '
 'as a breeding ground for suspect motives - personal, financial and possible '
 'grudges alike.\n'
 '\n'
 'Ernesto Ramirez, the apartment building maintenance worker, constantly found '
 'himself clashing with Wilkins over frequent maintenance requests. He felt '
 'slighted and disrespected, cultivating a deep-seated resentment towards her. '
 'Ramirez, finishing his shift at the apartment complex on the night of the '
 "murder, had unrestrained access to all residential units, including Wilkins' "
 'abode.\n'
 '\n'
 "Meanwhile, Maria Abery, Wilkins' former romantic interest and a Visual Arts "
 'Consultant, carried a bitter feud with her following a dramatic breakup. '
 'Their dispute took the form of a contentious custody battle over a shared '
 "pet, further fueled by a disdain for Wilkins' new relationship. Abery, seen "
 'near the crime scene on the night of the murder, had ample opportunity.\n'
 '\n'
 'Gary Schultz, a beleaguered Stock Marker Investor reported to have committed '
 'fraud against Wilkins, faced pressure from all sides. The threat of legal '
 'action from Wilkins could lead to imprisonment, further straining his mental '
 "state. Schultz, noticed at a diner across Wilkins' residence that fateful "
 'evening, seemed capable of homicide.\n'
 '\n'
 'However, in the dark clandestine world of criminality, the evidence pointed '
 "towards Ernesto Ramirez. Spurred by Schultz's sighting, a perceived "
 "antagonist to Wilkins, Ramirez's pent-up animosity transformed into an act "
 'of extreme rage. Utilizing his extensive accessibility to the building, he '
 "made his way into Wilkins' apartment.\n"
 '\n'
 'Evident resentment played a role. Perceived disrespect from constant '
 'maintenance requests and his frustration culminated violently within '
 'Ramirez. Spotting the climbing gear—a 47-inch Black Diamond ATC Belay '
 "Device—in Wilkins' house, Ramirez found his weapon of choice. His crime of "
 'passion, masked in the chaotic night, took the life of Amanda Wilkins, '
 'leaving behind a grim reminder of how personal misunderstandings can '
 'manifest into deadly ramifications.')

# Step 5 of 6 - prompt 29 ....2nd to last step: `case_characters`

- depends on `case_narrative`
- depends on `case_synopsis_md`

In [ ]:
character_case_relation = '"Culprit" || "Witness" || "Suspect" || "Victim" || "Incidental"'
prompt = get_prompt(29)
case_characters = generate_text(prompt, { "case_synopsis_md": case_synopsis_md, "role_options": character_case_relation,  "case_narrative": case_narrative})

# CaseMaker data format required for persisting data
pp.pprint(case_characters)

Prompt: You are a paralegal generating synthetic data for software to train legal prosecutors. Don't output markdown. Don't output three ticks. Just output the pure JSON array of characters.
- Each case should include 3-5 suspects. Ultimately, only one will be our killer. Each suspect should have a 4-5 sentence description, which includes:
    - The relationship between the suspect and the victim
    - Physical description, including age and build
    - Personality traits and overall demeanor
    - Profession
    - Vices
- The accuracy and level of detail in the suspect description can significantly impact the investigation. It is important to provide as much information as possible while avoiding assumptions or biases.
- In addition to having a personal connection to the victim, the suspects may also have personal relationships amongst one another, such as:
    - Sexual relationships or secret affairs
    - Friendships and enemies
    - Co-workers or former co-workers
- It is also possible that the suspects have no connective tissue between one another. Regardless, the relationships and qualities of these suspects must be grounded and realistic. A well-written suspect should be a three dimensional character with complex emotions, along with a detailed relationship and backstory with the victim.
- The killer is not yet revealed in the suspect character descriptions, but all must be equally plausible.

And the case synopsis:
{{case_synopsis_md}}

And the case narrative:
{{case_narrative}}

Generate just these roles: {{role_options}}
If only one role specified, create only characters of this role!

Create a new valid JSON describing the characters.
Follow this format:

[{
"sex": GENDER PRONOUNS // "male" || "female" || "intersex"
"role": {{role_options}}
"age": AGE,
"occupation": REALISTIC OBSCURE NAICS OCCUPATION,
"firstName": REALISTIC DIVERSE FIRST NAME,
"lastName": REALISTIC DIVERSE UNCOMMON LAST NAME,
"vices": List of vices and transgressions that define the character,
"relationships": triplets describing connections to other characters
"description": "Oscar Delgado, a 45-year-old Mexican-American librarian in San Francisco 2023, with a stout build, salt-and-pepper hair, and deep-set blue eyes behind round glasses, exudes a calm and contemplative aura, often seen with a thoughtful smile, and his gentle demeanor is betrayed only by the fiery passion he holds for historical mysteries, which he often shares with eager listeners.",
}]

Json: {'parameters': {'case_synopsis_md': "### Synopsis\n\nIn the quiet town of Southside District, San Jose, California, peace was disrupted when the lifeless body of a local resident, Amanda Wilkins, was discovered in her residence at 543 Elm Street at 11:45 pm on September 15, 2023. The autopsy report showed that the cause of Amanda Wilkin's death was strangulation. Alarmed by the disturbing sounds she'd heard earlier that night, Lucy Finch, a recluse and neighbor to the victim, alerted the local police at 12:34 am on September 16.\n\nTensions had been rising between Wilkins and a few individuals in the area due to a mixture of personal disputes, financial disagreements, and potential grudges. This made the unfolding crime scene tainted with strained emotions and potential motives, perfectly set for a sinister murder-mystery.\n\n### Characters\n\n- **Victim: Amanda Wilkins**, an Environmental Engineering Technician, whose life was abruptly taken in the sanctuary of her own home.\n- **Suspect 1: Ernesto Ramirez**, a building maintenance worker whose abrasive personality often put him at odds with the residents, especially Amanda Wilkins.\n- **Suspect 2: Maria Abery**, a Visual Arts Consultant and Wilkins' ex-partner, known for their public disagreements following their dramatic breakup.\n- **Suspect 3: Gary Schultz**, a distressed Stock Marker Investor who was recently accused of swindling considerable savings from Wilkins.\n- **Witness: Lucy Finch**, a relatively isolationist blogger who lived next door to the victim and alerted authorities after hearing disturbing noises from Wilkins' home.\n\n### Means, Motive & Opportunity\n\n- **Means:** Strangulation was the determined cause of death, specifically executed with a 47-inch Black Diamond ATC Belay Device, product SKU BD6200750000ALL1, commonly used in rock climbing.\n\n- **Motive:**\n    - **Ernesto Ramirez**: Ramirez harbored resentment for the victim stemming from her persistent maintenance complaints coupled with his perception of being disrespected.\n    - **Maria Abery**: Devastated by their failed relationship, Abery was locked in a bitter custody dispute over a shared pet, not to mention her disdain for Wilkins' new romantic interest.\n    - **Gary Schultz**: Schultz was under pressure as he faced accusations for defrauding Wilkins of a large sum of her savings and the looming threat of legal action from Wilkins could mean jail time.\n  \n- **Opportunity:**\n    - **Ernesto Ramirez**: As the apartment building's maintenance worker, Ramirez had unrestricted access to all the residential units.\n    - **Maria Abery**: Multiple sources reported seeing Abery in close proximity to the apartment complex on the evening of the homicide.\n    - **Gary Schultz**: Schultz was observed attending a meeting in a restaurant directly opposite Wilkins' residence the night the crime occurred.\n\n### The Night Of\n\nThe fatal night of September 15, 2023, appeared to start as any other evening for Amanda Wilkins as she returned from work, but before the night was over, her life would be cruelly snatched away. The neighborhood held its breath as the usual suspects emerged, each with their motive and opportunity. Ernesto Ramirez just finished his shift at the apartment building as he nursed a growing resentment for Wilkins. While Maria Abery, hoping to salvage any remaining warmth from their relationship before a legal decision severed their shared custody of Huckleberry, was close by. Gary Schultz, burdened by financial woes and potential fraud charges from Wilkins, was engaged in a heated discussion at a nearby restaurant.\n\nFate, though, determined that Ernesto Ramirez would be the orchestrator of the fatal ending. Witnessing Gary in the area from the building's doorman, a spike of anger drove him to seize the moment to settle his grievance against Wilkins. Infiltrating her residence, Ramirez found Wilkins' climbing gear - a 47-inch Black Diamond ATC Belay Device - and used it as the instrument of his wrath. \n\nRamirez, feeling repeatedly slighted by Wilkins' incessant maintenance complaints and viewing himself as the unjust target of disrespect, was consumed by rage. The appearance of Schultz, a stranger to Ramirez but known adversary to Wilkins, incensed his anger to murderous intent. Assuring himself the coast was clear, he snuck into Wilkin's apartment, executed his fatal act, and slipped away into the night.\n", 'role_options': '"Culprit" || "Witness" || "Suspect" || "Victim" || "Incidental"', 'case_narrative': "In the serene confines of Southside District, San Jose, tranquility shattered on September 15, 2023. The lifeless body of Amanda Wilkins, a local Environmental Engineering Technician, was found at her residence at 543 Elm Street at 11:45 pm. Lucy Finch, a hermit-like blogger living adjacent to Wilkins, alerted cops around 12:34 am on September 16, spurred by unusual noises she heard.\n\nAn autopsy determined the cause of death as strangulation, executed with a 47-inch Black Diamond ATC Belay Device, SKU BD6200750000ALL1, typically used in rock climbing. The convoluted web of relationships around Wilkins served as a breeding ground for suspect motives - personal, financial and possible grudges alike.\n\nErnesto Ramirez, the apartment building maintenance worker, constantly found himself clashing with Wilkins over frequent maintenance requests. He felt slighted and disrespected, cultivating a deep-seated resentment towards her. Ramirez, finishing his shift at the apartment complex on the night of the murder, had unrestrained access to all residential units, including Wilkins' abode.\n\nMeanwhile, Maria Abery, Wilkins' former romantic interest and a Visual Arts Consultant, carried a bitter feud with her following a dramatic breakup. Their dispute took the form of a contentious custody battle over a shared pet, further fueled by a disdain for Wilkins' new relationship. Abery, seen near the crime scene on the night of the murder, had ample opportunity.\n\nGary Schultz, a beleaguered Stock Marker Investor reported to have committed fraud against Wilkins, faced pressure from all sides. The threat of legal action from Wilkins could lead to imprisonment, further straining his mental state. Schultz, noticed at a diner across Wilkins' residence that fateful evening, seemed capable of homicide.\n\nHowever, in the dark clandestine world of criminality, the evidence pointed towards Ernesto Ramirez. Spurred by Schultz's sighting, a perceived antagonist to Wilkins, Ramirez's pent-up animosity transformed into an act of extreme rage. Utilizing his extensive accessibility to the building, he made his way into Wilkins' apartment.\n\nEvident resentment played a role. Perceived disrespect from constant maintenance requests and his frustration culminated violently within Ramirez. Spotting the climbing gear—a 47-inch Black Diamond ATC Belay Device—in Wilkins' house, Ramirez found his weapon of choice. His crime of passion, masked in the chaotic night, took the life of Amanda Wilkins, leaving behind a grim reminder of how personal misunderstandings can manifest into deadly ramifications."}, 'prompt': 'You are a paralegal generating synthetic data for software to train legal prosecutors. Don\'t output markdown. Don\'t output three ticks. Just output the pure JSON array of characters. \n- Each case should include 3-5 suspects. Ultimately, only one will be our killer. Each suspect should have a 4-5 sentence description, which includes:\n    - The relationship between the suspect and the victim\n    - Physical description, including age and build\n    - Personality traits and overall demeanor\n    - Profession\n    - Vices\n- The accuracy and level of detail in the suspect description can significantly impact the investigation. It is important to provide as much information as possible while avoiding assumptions or biases.\n- In addition to having a personal connection to the victim, the suspects may also have personal relationships amongst one another, such as:\n    - Sexual relationships or secret affairs\n    - Friendships and enemies\n    - Co-workers or former co-workers\n- It is also possible that the suspects have no connective tissue between one another. Regardless, the relationships and qualities of these suspects must be grounded and realistic. A well-written suspect should be a three dimensional character with complex emotions, along with a detailed relationship and backstory with the victim.\n- The killer is not yet revealed in the suspect character descriptions, but all must be equally plausible.\n\nAnd the case synopsis:\n{{case_synopsis_md}}\n\nAnd the case narrative:\n{{case_narrative}}\n\nGenerate just these roles: {{role_options}}\nIf only one role specified, create only characters of this role!\n\nCreate a new valid JSON describing the characters.\nFollow this format:\n\n[{\n"sex": GENDER PRONOUNS // "male" || "female" || "intersex"\n"role": {{role_options}}\n"age": AGE,\n"occupation": REALISTIC OBSCURE NAICS OCCUPATION,\n"firstName": REALISTIC DIVERSE FIRST NAME,\n"lastName": REALISTIC DIVERSE UNCOMMON LAST NAME,\n"vices": List of vices and transgressions that define the character,\n"relationships": triplets describing connections to other characters\n"description": "Oscar Delgado, a 45-year-old Mexican-American librarian in San Francisco 2023, with a stout build, salt-and-pepper hair, and deep-set blue eyes behind round glasses, exudes a calm and contemplative aura, often seen with a thoughtful smile, and his gentle demeanor is betrayed only by the fiery passion he holds for historical mysteries, which he often shares with eager listeners.",\n}]\n'}
[{'age': 37,
  'description': 'Ernesto Ramirez, a 37-year-old Mexican-American maintenance '
                 'worker for the apartment building in Southside District, is '
                 'a tall and robust man with a shaved head and dark '
                 'penetrating eyes. He holds a demeanor that often comes off '
                 'as abrasive with a propensity to harbor grudges, '
                 'particularly against those he feels are disrespectful or '
                 'demanding, like Amanda Wilkins.',
  'firstName': 'Ernesto',
  'lastName': 'Ramirez',
  'occupation': 'Building Maintenance Worker',
  'relationships': [['Amanda Wilkins',
                     'Victim',
                     "Maintained victim's building unit and often felt "
                     'disrespected by her']],
  'role': 'Culprit',
  'sex': 'male',
  'vices': ['Short-tempered', 'Harbors grudges', 'Disrespectful']},
 {'age': 44,
  'description': 'Lucy Finch, a 44-year-old Caucasian blogger, lives next door '
                 'to the late Amanda Wilkins. A slight woman with mousy brown '
                 'hair and glasses that magnify her worried blue eyes, she '
                 'prefers solitude and her online interactions over '
                 'socializing in person. Prone to anxiety and seen as somewhat '
                 'nosy by her neighbors, Lucy is the one who alerted '
                 "authorities to the unusual sounds from Amanda's house on the "
                 'night of the murder.',
  'firstName': 'Lucy',
  'lastName': 'Finch',
  'occupation': 'Blogger',
  'relationships': [['Amanda Wilkins',
                     'Victim',
                     'Lived next door to the victim and heard suspicious '
                     'noises the night of the murder']],
  'role': 'Witness',
  'sex': 'female',
  'vices': ['Recluse', 'Anxiety', 'Nosy']},
 {'age': 38,
  'description': 'Maria Abery, a stunning 38-year-old Visual Arts Consultant '
                 'with a slender frame and long, wavy raven hair, holds a '
                 'passionate nature which often veers into the realm of '
                 'possessiveness and jealousy, particularly in her romantic '
                 "relationships. She was Amanda Wilkin's former girlfriend and "
                 'their tumultuous breakup was well-known among their social '
                 'circles.',
  'firstName': 'Maria',
  'lastName': 'Abery',
  'occupation': 'Visual Arts Consultant',
  'relationships': [['Amanda Wilkins',
                     'Victim',
                     'Ex-girlfriend of victim, details of their contentious '
                     'breakup were public knowledge'],
                    ['Ernesto Ramirez',
                     'Culprit',
                     'Occasionally complained about service to the building '
                     'maintenance worker']],
  'role': 'Suspect',
  'sex': 'female',
  'vices': ['Temperamental', 'Jealous', 'Obsessive']},
 {'age': 52,
  'description': 'Gary Schultz, a 52-year-old stock market investor of '
                 'Germanic descent, is a somewhat chubby man with thinning '
                 'sandy brown hair and a deceptive charm that hides his more '
                 'ruthless nature. Known for his financial shrewdness which '
                 'often borders on illegality, he was recently accused by '
                 'Amanda Wilkins of defrauding her of a significant portion of '
                 'her savings.',
  'firstName': 'Gary',
  'lastName': 'Schultz',
  'occupation': 'Stock Market Investor',
  'relationships': [['Amanda Wilkins',
                     'Victim',
                     'Accused of defrauding the victim'],
                    ['Ernesto Ramirez',
                     'Culprit',
                     'Seen in the area on the night of the murder']],
  'role': 'Suspect',
  'sex': 'male',
  'vices': ['Greedy', 'Impulsive', 'Deceptive']},
 {'age': 30,
  'description': 'Amanda Wilkins, a 30-year-old Environmental Engineering '
                 'Technician was a lively, outspoken woman with a petite '
                 'figure and shoulder-length auburn hair. Known for her '
                 'headstrong nature and materialistic tendencies, her '
                 'tumultuous relationships with certain individuals in the '
                 'area were public knowledge before her life was abruptly '
                 'ended in her home.',
  'firstName': 'Amanda',
  'lastName': 'Wilkins',
  'occupation': 'Environmental Engineering Technician',
  'relationships': [['Ernesto Ramirez',
                     'Culprit',
                     'Resided in the building where Ernesto worked'],
                    ['Maria Abery', 'Suspect', 'Ex-girlfriend'],
                    ['Gary Schultz',
                     'Suspect',
                     'Believed Schultz defrauded her']],
  'role': 'Victim',
  'sex': 'female',
  'vices': ['Outspoken', 'Materialistic', 'Stubborn']}]

# Step 6 of 6: **new** case_events

- depends on `case_synopsis_md` which depends on `case_synopsis`
- depends on `case_characters`
- depends on `case_narrative` [ignored]

In [ ]:
# new events integration happens here!
events = get_new_events(synopsis=case_synopsis_md, characters=case_characters)
print(events)

200
[{'category': 'EVENT', 'charactersOnCasesUid': '', 'datetime': 'PLACEHOLDER', 'description': "On the night of September 15, 2023, in the quiet town of Southside District, San Jose, California, Amanda Wilkins, a 30-year-old Environmental Engineering Technician, returned home from work. Little did she know that this seemingly ordinary evening would be her last. As Amanda settled into her residence at 543 Elm Street, tensions brewed among the residents, creating a potential breeding ground for a sinister crime.\n\nAmong the individuals with motives and opportunity were three key suspects: Ernesto Ramirez, Maria Abery, and Gary Schultz. Ernesto Ramirez, a 37-year-old Mexican-American building maintenance worker, held a grudge against Amanda due to her persistent maintenance complaints and what he perceived as disrespect. Maria Abery, a Visual Arts Consultant and Amanda's ex-partner, was tangled in a bitter custody dispute over a shared pet and held disdain for Amanda's new romantic interest. Gary Schultz, a distressed Stock Market Investor, faced accusations of swindling significant savings from Amanda and the looming threat of legal action.\n\nThe means used to execute the murder was strangulation with a 47-inch Black Diamond ATC Belay Device, a product commonly used in rock climbing. This provided a diabolical twist to the crime scene.\n\nOn the fateful night, Ernesto Ramirez, having just finished his shift as the apartment building's maintenance worker, nursed his growing resentment towards Amanda. Witnessing Gary Schultz in the vicinity from the building's doorman, Ernesto felt a spike of anger and decided to seize the moment to settle his grievance.\n\nInfiltrating Amanda's residence, Ernesto discovered her climbing gear, including the 47-inch Black Diamond ATC Belay Device. Consumed by rage and fueled by his perception of being disrespected, Ernesto used the climbing gear as the instrument of his wrath. His anger intensified upon seeing Gary Schultz, whom he viewed as an adversary to Amanda, nearby.\n\nAfter ensuring the coast was clear, Ernesto sneaked into Amanda's apartment, confronted her, and executed his fatal act of strangulation. With the deed done, he slipped away into the night, leaving behind a lifeless body and a community in shock.\n\nLucy Finch, a recluse and neighbor to Amanda, heard disturbing noises from Amanda's home that night and promptly alerted the authorities, initiating a murder investigation that would unravel the sinister details of this crime.", 'name': 'Murder scene: Ernesto Ramirez kills Amanda Wilkins'}, {'category': 'EVENT', 'charactersOnCasesUid': '', 'datetime': 'PLACEHOLDER', 'description': "The victim, Amanda Wilkins, had given each of the suspects a motive to kill her.\n\nMaria Abery, Amanda's former girlfriend, had a tumultuous breakup with Amanda. Maria's possessiveness and jealousy in their relationship often caused problems. This could have been a motive for Maria to want Amanda dead.\n\nGary Schultz, a stock market investor, was accused by Amanda of defrauding her of a significant portion of her savings. This accusation could have fueled anger and resentment in Gary towards Amanda, giving him a motive to kill her.", 'name': 'Amanda Wilkins: victim start scene'}, {'category': 'OPPORTUNITY', 'charactersOnCasesUid': '', 'datetime': 'PLACEHOLDER', 'description': "Based on the evidence provided in the murder scene description, our suspect Maria Abery could not have had the opportunity to commit the murder of Amanda Wilkins. The description clearly states that Ernesto Ramirez, not Maria Abery, infiltrated Amanda's residence, discovered her climbing gear, and used the 47-inch Black Diamond ATC Belay Device to execute the strangulation. Maria Abery's presence or involvement in the crime scene is not mentioned, and there is no indication that she had access to Amanda's apartment or the climbing gear. Therefore, it can be concluded that Maria Abery did not have the opportunity to commit the murder.", 'name': 'Maria Abery had no opportunity'}, {'category': 'OPPORTUNITY', 'charactersOnCasesUid': '', 'datetime': 'PLACEHOLDER', 'description': "Based on the given context of the murder case, it is clear that our suspect, Gary Schultz, could not have had the opportunity to commit the murder of Amanda Wilkins. The timeline of events and the description of the crime scene provide a coherent and detailed account that proves beyond a doubt that Gary Schultz is not the perpetrator.\n\nAccording to the description of the murder scene, Ernesto Ramirez was the one who executed the murder of Amanda Wilkins. It is mentioned that Ernesto Ramirez infiltrated Amanda's residence after finishing his shift as the apartment building's maintenance worker. This indicates that Ernesto had direct access to Amanda's apartment and had the opportunity to commit the crime.\n\nOn the other hand, the description of Gary Schultz's involvement in the case states that he was merely in the vicinity of Amanda's residence, as witnessed by the building's doorman. There is no mention of Gary entering Amanda's apartment or having any direct contact with her. Additionally, the motive attributed to Gary is related to financial fraud, not personal grievances or disputes.\n\nTherefore, based on the evidence presented in the context, it is clear that Gary Schultz could not have had the opportunity to commit the murder of Amanda Wilkins. The focus of the investigation should be on Ernesto Ramirez and Maria Abery, who are the other two key suspects with motives and opportunities mentioned in the description of the murder scene.", 'name': 'Gary Schultz had no opportunity'}, {'category': 'OPPORTUNITY', 'charactersOnCasesUid': '', 'datetime': 'PLACEHOLDER', 'description': "Based on the evidence provided in the murder scene description, our suspect Maria Abery could not have had the opportunity to commit the murder of Amanda Wilkins. The description clearly states that Ernesto Ramirez, not Maria Abery, infiltrated Amanda's residence, discovered her climbing gear, and used the 47-inch Black Diamond ATC Belay Device to execute the strangulation. Maria Abery's presence or involvement in the crime scene is not mentioned, and there is no indication that she had access to Amanda's apartment or the climbing gear. Therefore, it can be concluded that Maria Abery did not have the opportunity to commit the murder.", 'name': 'Maria Abery maybe had opportunity'}, {'category': 'OPPORTUNITY', 'charactersOnCasesUid': '', 'datetime': 'PLACEHOLDER', 'description': "Based on the given context, it is clear that our suspect, Gary Schultz, could not have had the opportunity to commit the murder of Amanda Wilkins. The description of the murder scene indicates that Ernesto Ramirez, not Gary Schultz, executed the murder. Ernesto infiltrated Amanda's residence after finishing his shift as the apartment building's maintenance worker, giving him direct access to Amanda's apartment and the opportunity to commit the crime. In contrast, Gary Schultz was merely in the vicinity of Amanda's residence, according to the building's doorman. There is no mention of Gary entering Amanda's apartment or having any direct contact with her. Furthermore, Gary's motive is related to financial fraud, not personal grievances or disputes. Therefore, it is clear that Gary Schultz is not the perpetrator and the focus of the investigation should be on Ernesto Ramirez and Maria Abery, the other key suspects with motives and opportunities mentioned in the context.", 'name': 'Gary Schultz maybe had opportunity'}, {'category': 'MEANS', 'charactersOnCasesUid': '', 'datetime': 'PLACEHOLDER', 'description': "Based on the evidence from the earlier years of the suspect's life, Maria Abery, a Visual Arts Consultant and suspect in the murder of Amanda Wilkins, had the means to commit the murder. Maria was known to have a possessive and jealous nature, particularly in her romantic relationships, and had a tumultuous breakup with Amanda. On the night of the murder, Maria had the opportunity to access Amanda's residence and confront her. The murder weapon used, a 47-inch Black Diamond ATC Belay Device, was commonly used in rock climbing, and Maria had knowledge of Amanda's climbing gear, including this specific device. This suggests that Maria had knowledge of how to use the device for strangulation and had the means to carry out the crime. The evidence strongly implicates Maria Abery as the prime suspect in the murder of Amanda Wilkins.", 'name': 'Maria Abery had the means'}, {'category': 'MEANS', 'charactersOnCasesUid': '', 'datetime': 'PLACEHOLDER', 'description': "Based on the evidence from the earlier years of Gary Schultz's life, it is clear that he had the means to commit the murder of Amanda Wilkins. Gary Schultz, a 52-year-old stock market investor, is known for his financial shrewdness, which often borders on illegality. He was recently accused by Amanda Wilkins of defrauding her of a significant portion of her savings. This financial motive, combined with his deceptive charm and ruthless nature, provides a compelling reason to believe that Gary had the means to carry out the murder. Additionally, the murder weapon used, a 47-inch Black Diamond ATC Belay Device commonly used in rock climbing, suggests a level of familiarity with climbing gear that aligns with Gary's hobbies and interests. With these pieces of evidence, it is highly likely that Gary Schultz had the means to commit the murder.", 'name': 'Gary Schultz had the means'}, {'category': 'MOTIVE', 'charactersOnCasesUid': '', 'datetime': 'PLACEHOLDER', 'description': "During the investigation, it was discovered that Maria Abery had a strong alibi for the time of Amanda Wilkins' murder. On the night of the murder, Maria was attending an art gallery opening in downtown. Multiple witnesses confirmed seeing her at the event, including the event organizer and several art enthusiasts. Photos taken at the opening also showed Maria in attendance. The evidence of Maria's alibi casts doubt on her involvement in the murder and raises questions about her motive. If Maria had a solid alibi and was not present at the scene of the crime, it is unlikely that she would have had the opportunity to kill Amanda. This new information adds a layer of complexity to the investigation and suggests that the true motive and culprit may still be at large.", 'name': 'Maria Abery had a motive'}, {'category': 'MOTIVE', 'charactersOnCasesUid': '', 'datetime': 'PLACEHOLDER', 'description': "On a rainy evening in San Francisco, Amanda Wilkins decided to meet with Gary Schultz at a local cafe. As they sat down at a corner table, tension filled the air. Amanda confronted Gary about the accusations of fraud, demanding an explanation for her missing savings. The conversation quickly escalated into a heated argument, with both parties raising their voices and attracting curious glances from nearby patrons.\n\nAmanda's frustration and anger towards Gary were palpable, as she recounted the details of her financial loss and the impact it had on her life. She accused him of betraying her trust and vowed to take legal action to recover her money.\n\nGary, on the other hand, appeared unfazed by Amanda's accusations. He maintained a calm demeanor and attempted to dismiss her claims as baseless. He claimed innocence and insisted that Amanda must have misunderstood the situation.\n\nAs the argument reached its peak, Amanda slammed her hand on the table, causing her coffee cup to topple over and spill onto the floor. The commotion caught the attention of the cafe staff, who rushed over to clean up the mess.\n\nAfter a few moments of tense silence, Amanda abruptly got up from her seat, throwing a final glare at Gary before storming out of the cafe. Gary remained seated, seemingly unaffected by the confrontation.\n\nThis encounter between Amanda and Gary showcased the deep animosity and unresolved issues between them. It provided clear evidence of Gary's motive to harm Amanda, as his calm facade masked his underlying resentment and potentially dangerous intentions.", 'name': 'Gary Schultz had a motive'}]

# Step 6 of 6: **old** `case_events`

In [ ]:
prompt = get_prompt(22)
case_events = generate_text(prompt, {
    "synopsis": case_synopsis_md,
    "charactersData": case_characters,
    "narrative": case_narrative # ignore narrative for comparison evaluation of old and new event chains
    })
# CaseMaker data format required for persisting data
pp.pprint(case_events)

Prompt: You are a game designer developing crime game. Using the following investigation case:

Case name: {{caseName}}
Crime type: {{crimeType}}
Case location: {{location}}
Suspect number: {{suspectsNumber}}
Synopsis: {{synopsis}}
Introduction: {{introduction}}
Case characters data: {{charactersData}}
Narrative: {{narrative}}

Generate an array of events based on a case details, prioritize a narrative description as a source.
Generate 10-20 events.
Do not generate events for case solution, events should only lead to the solution.

Provide information following this JSON example:
[{
  name: 'string',
  description: 'string',
  datetime: 'date', // ISO string format
  category: 'MEANS' || 'OPPORTUNITY' || 'MOTIVE' || 'EVENT', // use just these values
  charactersOnCasesUid: 'uid' || undefined
}]

If generated event related with some character, take the "charactersOnCasesUid" field from that character data and place it into "charactersOnCasesUid" event's field.
If event is not related with any characters "charactersOnCasesUid" has to be omitted.
If event related with multiple characters pick the closest to the event.

return only json. do not return any instructions or explanation
Json: {'parameters': {'synopsis': "### Synopsis\n\nOn the evening of August 2, 2023, Mila Jensen, a 32-year old artist from San Francisco, met her untimely demise due to strangulation. The police received a call at 7:32 PM from her residence at the Bayview District, detailing an alarming occurrence of homicide at 2035 North Bay Ave. The dreadful discovery of Ms. Jensen's lifeless body was made by her close associate, Monica Ramirez, who placed the distress call to the authorities at approximately 7:25 PM. Prior to the horrific incident, unusual silence had prevailed as Ramirez failed to establish contact with Jensen for two days, a deviation from their regular interactions, prompting Monica to investigate in person.\n\n### Characters\n\n- **Mila Jensen** was a rising star in San Francisco's art scene, known for her unique approach to mixed-media sculptural creations. She led a reclusive lifestyle at the house where her body was found.\n\n- **Maurice 'Mo' Adler** is a prominent art critic known for his harsh reviews of contemporary works, including those of Mila Jensen.\n\n- **Tanya Lawson** is an ambitious fellow artist, a competitor in the creative field who often felt overshadowed by Ms. Jensen's success.\n\n- **Erik Stenberg** had been Ms. Jensen's romantic partner until their recent, bitter breakup.\n\n- **Monica Ramirez** is a fellow artist, and the one who found Ms. Jensen's body after two days of no contact.\n\n### Means, Motive & Opportunity\n\n- **Means:** Mila Jensen was brutally strangled using a nylon rope, specifically the Ace Hardware 3/8-Inch x 50-Feet Braided Nylon & Polyester Rope, SKU: ACBRD3850.\n\n- **Motive**\n    - **Maurice 'Mo' Adler:** His professional pride was hurt by Ms. Jensen's dismissive response to his critiques; He had possibly feared Ms. Jensen's growing influence on artistic norms.\n    - **Tanya Lawson:** Her growing resentment due to Jenkins' rapid rise to stardom; She had potentially perceived Mila's successes as hindrances to her own.\n    - **Erik Stenberg:** Their recent breakup might have stirred up feelings of resentment and anger; Erik might have harbored resentment due to perceived rejection.\n\n- **Opportunity**\n    - **Maurice 'Mo' Adler:** A trash receipt from a local convenience store places Adler in the Bayview District just hours before Mila's body was discovered.\n    - **Tanya Lawson:** Records from Mila's home security system show Lawson had visited the house a few days prior to the incident.\n    - **Erik Stenberg:** Call records indicate that Erik had a heated argument with Mila over the phone right on the night of the murder.\n\n### The Night Of\n\nOn the fateful night of August 2, 2023, Mila Jensen was alone at her residence, completely unaware of the darkness that was about to descend upon her life. Maurice 'Mo' Adler, a notable art critic and one of Mila's staunch critics, harbored deep resentment due to Jensen's rising popularity potentially threatening his influence on art. Adler was sighted in the Bayview District, just hours before the fatal event, as confirmed by a trash receipt from a local convenience store.\n\nAs the night grew darker, Adler seized his opportunity under the guise of a darkness that concealed his intentions at 2035 North Bay Ave. With the Ace Hardware 3/8-Inch x 50-Feet Braided Nylon & Polyester Rope, SKU: ACBRD3850, he ended Mila Jensen's life. Strangulation marks across Mila's neck painted a gruesome picture of the struggles she underwent in her final moments. Adler's final act was a commentary of fear - of an art critic fearing the shift in narrative and artistic power. Survival in this creative field, Adler believed, could only be ensured by eliminating the creative spark that threatened his hold over the art critique landscape.", 'charactersData': [{'sex': 'female', 'role': 'VICTIM', 'age': 32, 'occupation': 'Fine Artist', 'firstName': 'Mila', 'lastName': 'Jensen', 'vices': ['Reclusive', 'Sketchy Relationships'], 'description': 'Mila Jensen, a 32-year-old artist in San Francisco known for her mixed-media creativity, was a petite woman with long auburn hair and ceaseless energy housed in her sparkling eyes. Her introverted, calm, and persistent persona made her an enigma in the art world, often not engaging much with her peers.'}, {'sex': 'male', 'role': 'SUSPECT', 'age': 49, 'occupation': 'Art Critic', 'firstName': 'Maurice', 'lastName': 'Adler', 'vices': ['Smoker', 'Prideful'], 'relationships': [{'Mila Jensen': 'Critic'}], 'description': "Maurice 'Mo' Adler, a 49-year-old prominent art critic known for his harsh reviews, is a tall and broad man carrying an intimidating stature with an intense gaze. His perfectionist personality and dominating presence often stirs unease. He held a professional grudge against Mila after she dismissed his critiques."}, {'sex': 'female', 'role': 'SUSPECT', 'age': 30, 'occupation': 'Fine Artist', 'firstName': 'Tanya', 'lastName': 'Lawson', 'vices': ['Jealousy', 'Ambitious'], 'relationships': [{'Mila Jensen': 'Competitor'}], 'description': "Tanya Lawson, a 30-year-old ambitious fellow artist, is a tall individual with sharp features reflecting her competitive nature. Her fiery red hair complements her fierce personality. Tanya always felt overshadowed by Mila's rapid rise to stardom."}, {'sex': 'male', 'role': 'SUSPECT', 'age': 34, 'occupation': 'Software Developer', 'firstName': 'Erik', 'lastName': 'Stenberg', 'vices': ['Moody', 'Bitterness'], 'relationships': [{'Mila Jensen': 'Ex-Lover'}], 'description': "Erik Stenberg, Mila's ex-boyfriend, is a 34-year-old software developer. He has a lean figure, semi-long brown hair, and soft facial features. Hidden under his usually amiable personality are the bitterness and resentment from the painful breakup."}, {'sex': 'female', 'role': 'WITNESS', 'age': 31, 'occupation': 'Fine Artist', 'firstName': 'Monica', 'lastName': 'Ramirez', 'vices': ['Anxiety', 'Dependent'], 'relationships': [{'Mila Jensen': 'Close Associate'}], 'description': "Monica Ramirez, a 31-year-old artist and a close associate to Mila, is average built with long black hair. She often wears glasses that reflect her anxious and dependent personality. Monica was the one who found Mila’s body after increasingly worrying about Mila's unusual silence."}], 'narrative': "In late August 2022, Pacifica business owner Rowan Kearney made a dramatic discovery during an early morning jog. Kearney discovered the lifeless body of Koby Westfield, noted software engineer and co-founder of the renowned Bay Area start-up, Labyrinth Tech.\n\nAccording to the report issued by the Bay Area PD, Westfield, a resident of downtown San Francisco, was last seen leaving his office late in the evening on August 25th. His movements thereafter remained uncertain until his body was found near the shores of Pacifica.\n\nThe coroner's report confirmed that Westfield's death was a result of blunt force trauma to the skull, which marked the case as a homicide. Given the secluded location of the crime, the laceration's specific markings, and the precision of the blow, investigation shifted towards professionals with knowledge of anatomy.\n\nWestfield's colleagues at Labyrinth Tech—Cecelia Teague, a seasoned project manager, and Fitzroy Earnshaw, a fellow software engineer—emerged as primary suspects. Both had significant disputes with Westfield over company direction and intellectual property rights. Additionally, Teague, a former combat medic, and Earnshaw, an enthusiast of martial arts, possess knowledge of the human anatomy.\n\nUpon further investigation, detectives discovered an encrypted email thread between Westfield and local gym owner Brian Kirk, a gold medal Olympian shot-putter. The emails—mostly comprising of aggressive exchanges over financial disagreements—positioned Kirk as a third suspect. Moreover, the shot putter's strength and knowledge of projectile trajectory aligned with the lethal blow's characteristics.\n\nHowever, surveillance footage from Labyrinth Tech's office on the night of August 25th revealed Earnshaw leaving the office an hour before Westfield, discounting him as the culprit. Meanwhile, Teague's airtight alibi of attending a software convention in Los Angeles put her out of the suspect list. \n\nDespite an initial lack of hard evidence connecting Kirk to the crime, a breakthrough came from forensic analysis. Teams discovered a distinctive match between microscopic traces of unique gym chalk particles found on Kirk's shot puts and identical particles found on the victim's clothing. When confronted, Kirk's previously robust demeanor crumbled as he admitted to escalating a financial dispute into deadly violence. \n\nFollowing this confession, Brian Kirk was charged with the murder of Koby Westfield on September 16th, 2022. Westfield's untimely death has sent shockwaves through the tech industry, highlighting the sometimes turbulent and brutal realities lurking behind the bright facades of Silicon Valley start-ups."}, 'prompt': 'You are a game designer developing crime game. Using the following investigation case:\n\nCase name: {{caseName}}\nCrime type: {{crimeType}}\nCase location: {{location}}\nSuspect number: {{suspectsNumber}}\nSynopsis: {{synopsis}}\nIntroduction: {{introduction}}\nCase characters data: {{charactersData}}\nNarrative: {{narrative}}\n\nGenerate an array of events based on a case details, prioritize a narrative description as a source.\nGenerate 10-20 events.\nDo not generate events for case solution, events should only lead to the solution.\n\nProvide information following this JSON example:\n[{\n  name: \'string\',\n  description: \'string\',\n  datetime: \'date\', // ISO string format\n  category: \'MEANS\' || \'OPPORTUNITY\' || \'MOTIVE\' || \'EVENT\', // use just these values\n  charactersOnCasesUid: \'uid\' || undefined\n}]\n\nIf generated event related with some character, take the "charactersOnCasesUid" field from that character data and place it into "charactersOnCasesUid" event\'s field.\nIf event is not related with any characters "charactersOnCasesUid" has to be omitted.\nIf event related with multiple characters pick the closest to the event.\n\nreturn only json. do not return any instructions or explanation'}
[{'category': 'EVENT',
  'datetime': '2023-08-02T19:25:00.000Z',
  'description': 'Mila Jensen was found dead in her residence. The cause of '
                 'death was determined to be strangulation.',
  'name': "Mila Jensen's Murder"},
 {'category': 'EVENT',
  'charactersOnCasesUid': '5',
  'datetime': '2023-08-02T19:25:00.000Z',
  'description': 'Monica Ramirez discovers the lifeless body of Mila Jensen in '
                 'her residence and immediately contacts the authorities.',
  'name': "Monica Ramirez's Discovery"},
 {'category': 'OPPORTUNITY',
  'charactersOnCasesUid': '2',
  'datetime': '2023-08-02T15:00:00.000Z',
  'description': "A receipt from a local store confirms Maurice Adler's "
                 "presence in the Bayview District, just hours before Mila's "
                 'body was discovered.',
  'name': 'Maurice Adler in Bayview District'},
 {'category': 'MEANS',
  'datetime': '2023-08-02T20:00:00.000Z',
  'description': 'The murder weapon, a 3/8-Inch x 50-Feet Braided Nylon & '
                 'Polyester Rope, from Ace Hardware, is discovered at the '
                 'crime scene.',
  'name': 'Strangulation Tool Found'},
 {'category': 'MOTIVE',
  'charactersOnCasesUid': '4',
  'datetime': '2023-08-02T16:30:00.000Z',
  'description': 'Call records show a heated argument between Mila Jensen and '
                 'Erik Stenberg on the night of the murder.',
  'name': 'Argument Between Mila and Erik'},
 {'category': 'OPPORTUNITY',
  'charactersOnCasesUid': '3',
  'datetime': '2023-07-30T14:00:00.000Z',
  'description': "Security footage shows Tanya Lawson visited Mila's house a "
                 'few days prior to the incident.',
  'name': 'Tanya Lawson Visits Mila'},
 {'category': 'MOTIVE',
  'charactersOnCasesUid': '2',
  'datetime': '2023-07-10T12:00:00.000Z',
  'description': 'Previous encounters portray a pattern of disagreements and '
                 'professional tension between Mila Jensen and Maurice Adler.',
  'name': "Mila and Adler's Disagreements"},
 {'category': 'MOTIVE',
  'charactersOnCasesUid': '4',
  'datetime': '2023-07-20T00:00:00.000Z',
  'description': "Public knowledge of Mila and Erik's recent, bitter breakup.",
  'name': 'Breakup of Mila and Erik'},
 {'category': 'MOTIVE',
  'charactersOnCasesUid': '3',
  'datetime': '2023-08-01T20:00:00.000Z',
  'description': "Signs of Tanya Lawson's growing resentment towards Mila due "
                 "to the victim's rapid rise in the San Francisco's art scene "
                 'comes to surface.',
  'name': "Tanya Lawson's Resentment Towards Mila"}]

Generate event relations

In [ ]:
prompt = get_prompt(23)
events_relations = generate_text(prompt, {
    "narrative": case_narrative,
    "events": case_events
    })
# CaseMaker data format required for persisting data
pp.pprint(events_relations)

KeyError: ignored

Generate Concept Tree

In [ ]:
prompt = get_prompt(30)
case_tree = generate_text(prompt, {
    "case_synopsis_md": case_synopsis_md,
    "case_characters": case_characters
    })
# CaseMaker data format required for persisting data
md(case_tree)

Prompt: You are a paralegal generating synthetic data for software training legal prosecutors.
a concept tree for a court case would look like this:

<BEGIN CONCEPT TREE>
## Root
David "Grizzly" Sanchez murdered Lydia Garrison at her home by blunt force trauma inflicted by a baseball bat

## Branches

1. Concrete evidence:
        - Means: Baseball bat from victim's home used as the murder weapon
        - Motive: Argument at local pub and Sanchez's notorious temper
        - Opportunity: Sanchez followed Garrison to her residence from the pub

2. Character studies:
        - Lydia Garrison: A 52-year-old law professor at the University of San Francisco School of Law, described as dedicated, stern, assertive, and well-respected in her field
        - David "Grizzly" Sanchez: A 35-year-old blue-collar worker, habitual drinker, violent temper, known for trouble-making at bars
        - Mira Kwon: A 25-year-old law student at the University of San Francisco School of Law who has recently failed an exam and threatened Lydia publicly
        - Connie Lombardi: A fellow 58-year-old law professor known for her professional rivalry with Lydia

3. Police's understanding:
        - Lydia and Sanchez were involved in a heated argument in a local pub
        - Sanchez then followed Lydia and broke into her home where he murdered her
        - Fredrickson Hughes, Lydia's neighbor, was the one who reported the crime

4. Ground truth:
        - Transition from the bar to Garrison's home, Sanchez's infiltration, and the assault
        - Date and time of the murder: September 14, 2023, around 9:45 PM
        - Garrison's cause of death was blunt force trauma inflicted by a baseball bat

## Leaves:

1. Concrete evidence:
        - Sanchez's fingerprints were found on the baseball bat
        - Security footage from surrounding properties captured Sanchez tailing Garrison
        - Multiple witnesses confirming the argument between Sanchez and Garrison at the pub

2. Character studies:
        - Observations from coworkers and students about Garrison's dominant personality and professional impact
        - Reports from bar attendees and law enforcement about Sanchez's anger and drinking problem
        - Kwon’s threat to Garrison exhibited in her emails & statements from classmates confirming her anger
        - Lombardi seen leaving Lydia's neighborhood shortly before the crime - testimony from nearby residents

3. Police's understanding:
        - The statement from Hughes regarding the break-in at Lydia's residence
        - Various eyewitness accounts of the altercation between Sanchez and Lydia at the bar
        - Documentation from the initial investigation identifying Sanchez as one of the main suspects

4. Ground truth:
        - Lydia left the bar after an argument with Sanchez
        - Sanchez followed Lydia to her residence and broke into her house through a window
        - Sanchez hit Lydia with a bat causing her death before Hughes arrived.

<END CONCEPT TREE>

Given the case narrative:
{{case_synopsis_md}}

And the list of participants in the case:
{{case_characters}}


create a concept tree for this case.
Your generations must be compatible with the style presented by the San Francisco Police Department. You present only facts.

return the concept tree. Return the roots, branches, and Return minimum three leaves for each branch. Return in markdown outline format.  do not return any instructions or explanation. Format as markdown.
Json: {'parameters': {'case_synopsis_md': "### Synopsis\n\nOn the evening of August 2, 2023, Mila Jensen, a 32-year old artist from San Francisco, met her untimely demise due to strangulation. The police received a call at 7:32 PM from her residence at the Bayview District, detailing an alarming occurrence of homicide at 2035 North Bay Ave. The dreadful discovery of Ms. Jensen's lifeless body was made by her close associate, Monica Ramirez, who placed the distress call to the authorities at approximately 7:25 PM. Prior to the horrific incident, unusual silence had prevailed as Ramirez failed to establish contact with Jensen for two days, a deviation from their regular interactions, prompting Monica to investigate in person.\n\n### Characters\n\n- **Mila Jensen** was a rising star in San Francisco's art scene, known for her unique approach to mixed-media sculptural creations. She led a reclusive lifestyle at the house where her body was found.\n\n- **Maurice 'Mo' Adler** is a prominent art critic known for his harsh reviews of contemporary works, including those of Mila Jensen.\n\n- **Tanya Lawson** is an ambitious fellow artist, a competitor in the creative field who often felt overshadowed by Ms. Jensen's success.\n\n- **Erik Stenberg** had been Ms. Jensen's romantic partner until their recent, bitter breakup.\n\n- **Monica Ramirez** is a fellow artist, and the one who found Ms. Jensen's body after two days of no contact.\n\n### Means, Motive & Opportunity\n\n- **Means:** Mila Jensen was brutally strangled using a nylon rope, specifically the Ace Hardware 3/8-Inch x 50-Feet Braided Nylon & Polyester Rope, SKU: ACBRD3850.\n\n- **Motive**\n    - **Maurice 'Mo' Adler:** His professional pride was hurt by Ms. Jensen's dismissive response to his critiques; He had possibly feared Ms. Jensen's growing influence on artistic norms.\n    - **Tanya Lawson:** Her growing resentment due to Jenkins' rapid rise to stardom; She had potentially perceived Mila's successes as hindrances to her own.\n    - **Erik Stenberg:** Their recent breakup might have stirred up feelings of resentment and anger; Erik might have harbored resentment due to perceived rejection.\n\n- **Opportunity**\n    - **Maurice 'Mo' Adler:** A trash receipt from a local convenience store places Adler in the Bayview District just hours before Mila's body was discovered.\n    - **Tanya Lawson:** Records from Mila's home security system show Lawson had visited the house a few days prior to the incident.\n    - **Erik Stenberg:** Call records indicate that Erik had a heated argument with Mila over the phone right on the night of the murder.\n\n### The Night Of\n\nOn the fateful night of August 2, 2023, Mila Jensen was alone at her residence, completely unaware of the darkness that was about to descend upon her life. Maurice 'Mo' Adler, a notable art critic and one of Mila's staunch critics, harbored deep resentment due to Jensen's rising popularity potentially threatening his influence on art. Adler was sighted in the Bayview District, just hours before the fatal event, as confirmed by a trash receipt from a local convenience store.\n\nAs the night grew darker, Adler seized his opportunity under the guise of a darkness that concealed his intentions at 2035 North Bay Ave. With the Ace Hardware 3/8-Inch x 50-Feet Braided Nylon & Polyester Rope, SKU: ACBRD3850, he ended Mila Jensen's life. Strangulation marks across Mila's neck painted a gruesome picture of the struggles she underwent in her final moments. Adler's final act was a commentary of fear - of an art critic fearing the shift in narrative and artistic power. Survival in this creative field, Adler believed, could only be ensured by eliminating the creative spark that threatened his hold over the art critique landscape.", 'case_characters': [{'sex': 'female', 'role': 'VICTIM', 'age': 32, 'occupation': 'Fine Artist', 'firstName': 'Mila', 'lastName': 'Jensen', 'vices': ['Reclusive', 'Sketchy Relationships'], 'description': 'Mila Jensen, a 32-year-old artist in San Francisco known for her mixed-media creativity, was a petite woman with long auburn hair and ceaseless energy housed in her sparkling eyes. Her introverted, calm, and persistent persona made her an enigma in the art world, often not engaging much with her peers.'}, {'sex': 'male', 'role': 'SUSPECT', 'age': 49, 'occupation': 'Art Critic', 'firstName': 'Maurice', 'lastName': 'Adler', 'vices': ['Smoker', 'Prideful'], 'relationships': [{'Mila Jensen': 'Critic'}], 'description': "Maurice 'Mo' Adler, a 49-year-old prominent art critic known for his harsh reviews, is a tall and broad man carrying an intimidating stature with an intense gaze. His perfectionist personality and dominating presence often stirs unease. He held a professional grudge against Mila after she dismissed his critiques."}, {'sex': 'female', 'role': 'SUSPECT', 'age': 30, 'occupation': 'Fine Artist', 'firstName': 'Tanya', 'lastName': 'Lawson', 'vices': ['Jealousy', 'Ambitious'], 'relationships': [{'Mila Jensen': 'Competitor'}], 'description': "Tanya Lawson, a 30-year-old ambitious fellow artist, is a tall individual with sharp features reflecting her competitive nature. Her fiery red hair complements her fierce personality. Tanya always felt overshadowed by Mila's rapid rise to stardom."}, {'sex': 'male', 'role': 'SUSPECT', 'age': 34, 'occupation': 'Software Developer', 'firstName': 'Erik', 'lastName': 'Stenberg', 'vices': ['Moody', 'Bitterness'], 'relationships': [{'Mila Jensen': 'Ex-Lover'}], 'description': "Erik Stenberg, Mila's ex-boyfriend, is a 34-year-old software developer. He has a lean figure, semi-long brown hair, and soft facial features. Hidden under his usually amiable personality are the bitterness and resentment from the painful breakup."}, {'sex': 'female', 'role': 'WITNESS', 'age': 31, 'occupation': 'Fine Artist', 'firstName': 'Monica', 'lastName': 'Ramirez', 'vices': ['Anxiety', 'Dependent'], 'relationships': [{'Mila Jensen': 'Close Associate'}], 'description': "Monica Ramirez, a 31-year-old artist and a close associate to Mila, is average built with long black hair. She often wears glasses that reflect her anxious and dependent personality. Monica was the one who found Mila’s body after increasingly worrying about Mila's unusual silence."}]}, 'prompt': 'You are a paralegal generating synthetic data for software training legal prosecutors.\na concept tree for a court case would look like this:\n\n<BEGIN CONCEPT TREE>\n## Root\nDavid "Grizzly" Sanchez murdered Lydia Garrison at her home by blunt force trauma inflicted by a baseball bat\n\n## Branches\n\n1. Concrete evidence:\n        - Means: Baseball bat from victim\'s home used as the murder weapon\n        - Motive: Argument at local pub and Sanchez\'s notorious temper\n        - Opportunity: Sanchez followed Garrison to her residence from the pub\n\n2. Character studies:\n        - Lydia Garrison: A 52-year-old law professor at the University of San Francisco School of Law, described as dedicated, stern, assertive, and well-respected in her field\n        - David "Grizzly" Sanchez: A 35-year-old blue-collar worker, habitual drinker, violent temper, known for trouble-making at bars\n        - Mira Kwon: A 25-year-old law student at the University of San Francisco School of Law who has recently failed an exam and threatened Lydia publicly\n        - Connie Lombardi: A fellow 58-year-old law professor known for her professional rivalry with Lydia\n\n3. Police\'s understanding:\n        - Lydia and Sanchez were involved in a heated argument in a local pub\n        - Sanchez then followed Lydia and broke into her home where he murdered her\n        - Fredrickson Hughes, Lydia\'s neighbor, was the one who reported the crime\n\n4. Ground truth:\n        - Transition from the bar to Garrison\'s home, Sanchez\'s infiltration, and the assault\n        - Date and time of the murder: September 14, 2023, around 9:45 PM\n        - Garrison\'s cause of death was blunt force trauma inflicted by a baseball bat\n\n## Leaves:\n\n1. Concrete evidence:\n        - Sanchez\'s fingerprints were found on the baseball bat\n        - Security footage from surrounding properties captured Sanchez tailing Garrison\n        - Multiple witnesses confirming the argument between Sanchez and Garrison at the pub\n\n2. Character studies:\n        - Observations from coworkers and students about Garrison\'s dominant personality and professional impact\n        - Reports from bar attendees and law enforcement about Sanchez\'s anger and drinking problem\n        - Kwon’s threat to Garrison exhibited in her emails & statements from classmates confirming her anger\n        - Lombardi seen leaving Lydia\'s neighborhood shortly before the crime - testimony from nearby residents\n\n3. Police\'s understanding:\n        - The statement from Hughes regarding the break-in at Lydia\'s residence\n        - Various eyewitness accounts of the altercation between Sanchez and Lydia at the bar\n        - Documentation from the initial investigation identifying Sanchez as one of the main suspects\n\n4. Ground truth:\n        - Lydia left the bar after an argument with Sanchez\n        - Sanchez followed Lydia to her residence and broke into her house through a window\n        - Sanchez hit Lydia with a bat causing her death before Hughes arrived.\n\n<END CONCEPT TREE>\n\nGiven the case narrative:\n{{case_synopsis_md}}\n\nAnd the list of participants in the case:\n{{case_characters}}\n\n\ncreate a concept tree for this case.\nYour generations must be compatible with the style presented by the San Francisco Police Department. You present only facts.\n\nreturn the concept tree. Return the roots, branches, and Return minimum three leaves for each branch. Return in markdown outline format.  do not return any instructions or explanation. Format as markdown.'}

<BEGIN CONCEPT TREE>

## Root
Mila Jensen was murdered in her San Francisco home, asphyxiated using a nylon rope.

## Branches

1. Concrete evidence:
     - Means: Death by strangulation using a 3/8-Inch x 50-Feet Braided Nylon & Polyester Rope
     - Motive: Stemmed from professional competition, professional criticism, and personal conflict
     - Opportunity: Adler seen nearby hours before, Lawson visited home days prior, Stenberg had heated phone call on the night

2. Character studies:
     - Mila Jensen: A 32-year-old artist, flourishing in her field, preferring her solitude
     - Maurice 'Mo' Adler: A 49-year-old renowned art critic, known for his ruthless critiques, held a professional grudge against Jensen
     - Tanya Lawson: A 30-year-old ambitious fellow artist, felt overshadowed by Jensen's rapidly rising success
     - Erik Stenberg: A 34-year-old software developer, suffered a recent, bitter breakup with Jensen
     - Monica Ramirez: A 31-year-old fellow artist, discovered Jensen's body after observing her unusual silence

3. Police's understanding:
     - Suspects identified based on motives relating to professional rivalries and personal animosities
     - The art critic Adler was in the vicinity before the murder
     - Ramirez placed the distress call at 7:25 PM after finding Jensen's body

4. Ground truth:
     - Transition of events leading to the discovery of Jensen's murdered body at her residence
     - Date and time of the murder: August 2, 2023, approximated to take place before 7:25 PM
     - Jensen's cause of death was asphyxiation by the use of a nylon rope

## Leaves:

1. Concrete evidence:
     - Nylon rope identified as murder weapon, purchase and possession of which to be probed
     - Investigation of Adler's presence in the Bayview District hours before the murder
     - Recording of heated argument between Stenberg and Jensen on the night of the murder

2. Character studies:
     - Observations of Jensen’s supposed reclusive lifestyle tied against her rising popularity
     - Adler’s animosity towards Jensen’s dismissive response to his critiques
     - Lawson’s competition and jealousy hypothesis analyzed against her visit to Jensen’s house a few days prior
     - Analysis of Stenberg’s recent breakup and its potential connection to the murder

3. Police's understanding:
     - Evaluation of incoming distress call and Ramirez’s discovery of Jensen’s body
     - Review of all possible motives behind the murder, establishing a sequence of seemingly hostile events
     - Probing Adler’s receipt from a local store which pins his location near the scene hours before the incident

4. Ground truth:
     - Recreating the probable sequence of events on August 2, 2023, based on available circumstantial evidence
     - Time of death to be cross-verified against Ramirez’s distress call timing
     - Autopsy report confirming asphyxiation due to strangulation

<END CONCEPT TREE>

In [ ]:
prompt = get_prompt(32)
case_solution = generate_text(prompt, {
    "case_synopsis_md": case_synopsis_md,
    "case_characters": case_characters,
    "case_tree": case_tree
    })
# CaseMaker data format required for persisting data
md(case_solution)

Prompt: You are a game designer developing crime game. Using the following crime case:

Your generations must be compatible with the style presented by the San Francisco Police Department. You present only facts.

Given case details described as this:

{{case_synopsis_md}}

And the list of characters on the case described as this:
{{case_characters}}

the original timeline of events:
{{case_tree}}

give me the solution to the game explicitly. finish writing the solution and make it concrete if it is not obvious.
it needs a culprit, means, motive, opportunity. The means must crisply define the murder weapon is one exists.
return your answer in markdown only. return only markdown.
markdown:
Json: {'parameters': {'case_synopsis_md': "### Synopsis\n\nOn the evening of August 2, 2023, Mila Jensen, a 32-year old artist from San Francisco, met her untimely demise due to strangulation. The police received a call at 7:32 PM from her residence at the Bayview District, detailing an alarming occurrence of homicide at 2035 North Bay Ave. The dreadful discovery of Ms. Jensen's lifeless body was made by her close associate, Monica Ramirez, who placed the distress call to the authorities at approximately 7:25 PM. Prior to the horrific incident, unusual silence had prevailed as Ramirez failed to establish contact with Jensen for two days, a deviation from their regular interactions, prompting Monica to investigate in person.\n\n### Characters\n\n- **Mila Jensen** was a rising star in San Francisco's art scene, known for her unique approach to mixed-media sculptural creations. She led a reclusive lifestyle at the house where her body was found.\n\n- **Maurice 'Mo' Adler** is a prominent art critic known for his harsh reviews of contemporary works, including those of Mila Jensen.\n\n- **Tanya Lawson** is an ambitious fellow artist, a competitor in the creative field who often felt overshadowed by Ms. Jensen's success.\n\n- **Erik Stenberg** had been Ms. Jensen's romantic partner until their recent, bitter breakup.\n\n- **Monica Ramirez** is a fellow artist, and the one who found Ms. Jensen's body after two days of no contact.\n\n### Means, Motive & Opportunity\n\n- **Means:** Mila Jensen was brutally strangled using a nylon rope, specifically the Ace Hardware 3/8-Inch x 50-Feet Braided Nylon & Polyester Rope, SKU: ACBRD3850.\n\n- **Motive**\n    - **Maurice 'Mo' Adler:** His professional pride was hurt by Ms. Jensen's dismissive response to his critiques; He had possibly feared Ms. Jensen's growing influence on artistic norms.\n    - **Tanya Lawson:** Her growing resentment due to Jenkins' rapid rise to stardom; She had potentially perceived Mila's successes as hindrances to her own.\n    - **Erik Stenberg:** Their recent breakup might have stirred up feelings of resentment and anger; Erik might have harbored resentment due to perceived rejection.\n\n- **Opportunity**\n    - **Maurice 'Mo' Adler:** A trash receipt from a local convenience store places Adler in the Bayview District just hours before Mila's body was discovered.\n    - **Tanya Lawson:** Records from Mila's home security system show Lawson had visited the house a few days prior to the incident.\n    - **Erik Stenberg:** Call records indicate that Erik had a heated argument with Mila over the phone right on the night of the murder.\n\n### The Night Of\n\nOn the fateful night of August 2, 2023, Mila Jensen was alone at her residence, completely unaware of the darkness that was about to descend upon her life. Maurice 'Mo' Adler, a notable art critic and one of Mila's staunch critics, harbored deep resentment due to Jensen's rising popularity potentially threatening his influence on art. Adler was sighted in the Bayview District, just hours before the fatal event, as confirmed by a trash receipt from a local convenience store.\n\nAs the night grew darker, Adler seized his opportunity under the guise of a darkness that concealed his intentions at 2035 North Bay Ave. With the Ace Hardware 3/8-Inch x 50-Feet Braided Nylon & Polyester Rope, SKU: ACBRD3850, he ended Mila Jensen's life. Strangulation marks across Mila's neck painted a gruesome picture of the struggles she underwent in her final moments. Adler's final act was a commentary of fear - of an art critic fearing the shift in narrative and artistic power. Survival in this creative field, Adler believed, could only be ensured by eliminating the creative spark that threatened his hold over the art critique landscape.", 'case_characters': [{'sex': 'female', 'role': 'VICTIM', 'age': 32, 'occupation': 'Fine Artist', 'firstName': 'Mila', 'lastName': 'Jensen', 'vices': ['Reclusive', 'Sketchy Relationships'], 'description': 'Mila Jensen, a 32-year-old artist in San Francisco known for her mixed-media creativity, was a petite woman with long auburn hair and ceaseless energy housed in her sparkling eyes. Her introverted, calm, and persistent persona made her an enigma in the art world, often not engaging much with her peers.'}, {'sex': 'male', 'role': 'SUSPECT', 'age': 49, 'occupation': 'Art Critic', 'firstName': 'Maurice', 'lastName': 'Adler', 'vices': ['Smoker', 'Prideful'], 'relationships': [{'Mila Jensen': 'Critic'}], 'description': "Maurice 'Mo' Adler, a 49-year-old prominent art critic known for his harsh reviews, is a tall and broad man carrying an intimidating stature with an intense gaze. His perfectionist personality and dominating presence often stirs unease. He held a professional grudge against Mila after she dismissed his critiques."}, {'sex': 'female', 'role': 'SUSPECT', 'age': 30, 'occupation': 'Fine Artist', 'firstName': 'Tanya', 'lastName': 'Lawson', 'vices': ['Jealousy', 'Ambitious'], 'relationships': [{'Mila Jensen': 'Competitor'}], 'description': "Tanya Lawson, a 30-year-old ambitious fellow artist, is a tall individual with sharp features reflecting her competitive nature. Her fiery red hair complements her fierce personality. Tanya always felt overshadowed by Mila's rapid rise to stardom."}, {'sex': 'male', 'role': 'SUSPECT', 'age': 34, 'occupation': 'Software Developer', 'firstName': 'Erik', 'lastName': 'Stenberg', 'vices': ['Moody', 'Bitterness'], 'relationships': [{'Mila Jensen': 'Ex-Lover'}], 'description': "Erik Stenberg, Mila's ex-boyfriend, is a 34-year-old software developer. He has a lean figure, semi-long brown hair, and soft facial features. Hidden under his usually amiable personality are the bitterness and resentment from the painful breakup."}, {'sex': 'female', 'role': 'WITNESS', 'age': 31, 'occupation': 'Fine Artist', 'firstName': 'Monica', 'lastName': 'Ramirez', 'vices': ['Anxiety', 'Dependent'], 'relationships': [{'Mila Jensen': 'Close Associate'}], 'description': "Monica Ramirez, a 31-year-old artist and a close associate to Mila, is average built with long black hair. She often wears glasses that reflect her anxious and dependent personality. Monica was the one who found Mila’s body after increasingly worrying about Mila's unusual silence."}], 'case_tree': "<BEGIN CONCEPT TREE>\n\n## Root\nMila Jensen was murdered in her San Francisco home, asphyxiated using a nylon rope.\n\n## Branches\n\n1. Concrete evidence:\n     - Means: Death by strangulation using a 3/8-Inch x 50-Feet Braided Nylon & Polyester Rope\n     - Motive: Stemmed from professional competition, professional criticism, and personal conflict\n     - Opportunity: Adler seen nearby hours before, Lawson visited home days prior, Stenberg had heated phone call on the night\n\n2. Character studies:\n     - Mila Jensen: A 32-year-old artist, flourishing in her field, preferring her solitude\n     - Maurice 'Mo' Adler: A 49-year-old renowned art critic, known for his ruthless critiques, held a professional grudge against Jensen\n     - Tanya Lawson: A 30-year-old ambitious fellow artist, felt overshadowed by Jensen's rapidly rising success\n     - Erik Stenberg: A 34-year-old software developer, suffered a recent, bitter breakup with Jensen\n     - Monica Ramirez: A 31-year-old fellow artist, discovered Jensen's body after observing her unusual silence\n     \n3. Police's understanding:\n     - Suspects identified based on motives relating to professional rivalries and personal animosities\n     - The art critic Adler was in the vicinity before the murder\n     - Ramirez placed the distress call at 7:25 PM after finding Jensen's body\n\n4. Ground truth:\n     - Transition of events leading to the discovery of Jensen's murdered body at her residence\n     - Date and time of the murder: August 2, 2023, approximated to take place before 7:25 PM\n     - Jensen's cause of death was asphyxiation by the use of a nylon rope\n\n## Leaves:\n\n1. Concrete evidence:\n     - Nylon rope identified as murder weapon, purchase and possession of which to be probed\n     - Investigation of Adler's presence in the Bayview District hours before the murder\n     - Recording of heated argument between Stenberg and Jensen on the night of the murder\n\n2. Character studies:\n     - Observations of Jensen’s supposed reclusive lifestyle tied against her rising popularity\n     - Adler’s animosity towards Jensen’s dismissive response to his critiques\n     - Lawson’s competition and jealousy hypothesis analyzed against her visit to Jensen’s house a few days prior\n     - Analysis of Stenberg’s recent breakup and its potential connection to the murder\n\n3. Police's understanding:\n     - Evaluation of incoming distress call and Ramirez’s discovery of Jensen’s body\n     - Review of all possible motives behind the murder, establishing a sequence of seemingly hostile events\n     - Probing Adler’s receipt from a local store which pins his location near the scene hours before the incident\n\n4. Ground truth:\n     - Recreating the probable sequence of events on August 2, 2023, based on available circumstantial evidence\n     - Time of death to be cross-verified against Ramirez’s distress call timing\n     - Autopsy report confirming asphyxiation due to strangulation\n\n<END CONCEPT TREE>\n"}, 'prompt': 'You are a game designer developing crime game. Using the following crime case:\n\nYour generations must be compatible with the style presented by the San Francisco Police Department. You present only facts.\n\nGiven case details described as this:\n\n{{case_synopsis_md}}\n\nAnd the list of characters on the case described as this:\n{{case_characters}}\n\nthe original timeline of events:\n{{case_tree}}\n\ngive me the solution to the game explicitly. finish writing the solution and make it concrete if it is not obvious.\nit needs a culprit, means, motive, opportunity. The means must crisply define the murder weapon is one exists.\nreturn your answer in markdown only. return only markdown.\nmarkdown:'}

# Solution

## Culprit
The murder case has three primary suspects - Maurice 'Mo' Adler, Tanya Lawson, and Erik Stenberg. After careful consideration of all the motivations, available evidence, and timelines, it is evident that Maurice 'Mo' Adler, the renowned art critic, is the culprit in the death of Mila Jensen.

## Means
The art critic Adler used an Ace Hardware 3/8-Inch x 50-Feet Braided Nylon & Polyester Rope, SKU: ACBRD3850 to strangle Mila Jensen. This was confirmed during the investigation and subsequently validated by an autopsy report confirming asphyxiation due to strangulation - a detail that aligns with the use of the rope. The rope, thus, was the murder weapon used by Adler to commit the heinous act.

## Motive
Adler's professional pride was hurt when Mila Jensen dismissed his harsh critiques of her work. As an upcoming artist, Jensen was rapidly gaining popularity, which Adler might have perceived as a threat to his influential position within the art scene. The fear of losing his standing and the resentment against Jensen's dismissive attitude cumulatively built up the motive for Adler to eliminate Jensen.

## Opportunity
A receipt obtained from a local convenience store placed Maurice 'Mo' Adler in the Bayview District, in the vicinity of Jensen's residence, hours before body was found. This provided him with the golden opportunity to commit the murder. The time elapsed between Adler's appearance in the district and the subsequent distress call made by Ramirez creates a believable time window for Adler to carry out the act and cover his tracks, making him the prime suspect in this murder.

In [ ]:
prompt = get_prompt(33)
evidence_tier3 = generate_text(prompt, {
    "case_synopsis_md": case_synopsis_md,
    "case_characters": case_characters,
    "case_tree": case_tree,
    "case_solution": case_solution
    })
# CaseMaker data format required for persisting data
pp.pprint(evidence_tier3)

Prompt: You are a game designer developing crime game.
Your generations must be compatible with the style presented by the San Francisco Police Department. You present only facts.
Using the following crime case:

Given case details described as this:
{{case_synopsis_md}}

And the list of characters on the case described as this:
{{case_characters}}

The case concept tree:
{{case_tree}}

the game solution:
{{case_solution}}


Consider a board of UI cards representing evidence.
There are 4 tiers and a solution. Each tier is a column in the kanban.

Tier 0 is the initial information to flesh out the case. Tier 0 Types: 1. Synopsis 2. Introduction 3. Crime Scene Photo 4. Forensic Reports 5. CCTV photos 6. Witness 7. Victims

Tier 1 consists of a Police Interview transcript for each witness and suspect. Some of these may later be converted to audio or video. The number of cards must equal the number of suspects. Invent new suspects with full names, motivations, and relationships to existing characters.

Tier 2 provides a clearer picture of motive and the relationships between the suspects, witnesses, victim through their correspondence, interactions, and actions. Tier 2 will provide details to whether alibis are true or the suspects are lying. Tier 2 will provide deeper insight into the personalities of the suspects and victim through their interactions. Tier 2 types include: 1. SMS or other text message types 2. Emails 3. Social media direct messages or posts 4. CCTV photos 5. Voice calls, recordings, and voicemails 6. geolocation or other electronic logging

Tier 3 provides evidence that is indisputable and fact based. Tier 3 will provide facts of the case that will subtly reveal discrepancies in the information given by the suspects in Tier 1 and Tier 2. Consider the possibility of documents and facts found by the detectives in a later stage of the case. Tier 3 are more obscure pieces of evidence and could vary wildly depending on the details of the case.

Tier 3 must point toward the solution to the case.
Solution Cards are the last column in the case evidence board and describe the ground truth of what happened, used to power the software.
There is a means card, a motive card, an opportunity card and a culprit card.

Provide information following this JSON example:
{{
"tiers": [
{{
 "tier_0": [
{{"card_type": "card type", "card_text": "card text"}},
{{{{"card_type": "card type", "card_text": "card text"}}
]}},
{{"tier_1": [
{{{{"card_type": "card type", "card_text": "card text"}},
{{{{"card_type": "card type", "card_text": "card text"}}
]}}
],
"solutions": [
{{"means":"mean details"}},
{{"motive":"motive details"}},
{{"opportunity":"opportunity details"}},
{{"culprit":"culprit details"}}
]
}}

Example of the generated card:
{{"card_type": "Physical Evidence", "card_text": "A police evidence photo of the murder weapon, a rusty fishing knife with dried blood on the blade and handle"}}

create all tier 3 cards. Generate Solution cards.
do not generate tier 0
do not generate tier 1
do not generate tier 2

return only json. do not return any instructions or explanation

do not say "Json:" start with a bracket or brace.
Json: {'parameters': {'case_synopsis_md': "### Synopsis\n\nOn the evening of August 2, 2023, Mila Jensen, a 32-year old artist from San Francisco, met her untimely demise due to strangulation. The police received a call at 7:32 PM from her residence at the Bayview District, detailing an alarming occurrence of homicide at 2035 North Bay Ave. The dreadful discovery of Ms. Jensen's lifeless body was made by her close associate, Monica Ramirez, who placed the distress call to the authorities at approximately 7:25 PM. Prior to the horrific incident, unusual silence had prevailed as Ramirez failed to establish contact with Jensen for two days, a deviation from their regular interactions, prompting Monica to investigate in person.\n\n### Characters\n\n- **Mila Jensen** was a rising star in San Francisco's art scene, known for her unique approach to mixed-media sculptural creations. She led a reclusive lifestyle at the house where her body was found.\n\n- **Maurice 'Mo' Adler** is a prominent art critic known for his harsh reviews of contemporary works, including those of Mila Jensen.\n\n- **Tanya Lawson** is an ambitious fellow artist, a competitor in the creative field who often felt overshadowed by Ms. Jensen's success.\n\n- **Erik Stenberg** had been Ms. Jensen's romantic partner until their recent, bitter breakup.\n\n- **Monica Ramirez** is a fellow artist, and the one who found Ms. Jensen's body after two days of no contact.\n\n### Means, Motive & Opportunity\n\n- **Means:** Mila Jensen was brutally strangled using a nylon rope, specifically the Ace Hardware 3/8-Inch x 50-Feet Braided Nylon & Polyester Rope, SKU: ACBRD3850.\n\n- **Motive**\n    - **Maurice 'Mo' Adler:** His professional pride was hurt by Ms. Jensen's dismissive response to his critiques; He had possibly feared Ms. Jensen's growing influence on artistic norms.\n    - **Tanya Lawson:** Her growing resentment due to Jenkins' rapid rise to stardom; She had potentially perceived Mila's successes as hindrances to her own.\n    - **Erik Stenberg:** Their recent breakup might have stirred up feelings of resentment and anger; Erik might have harbored resentment due to perceived rejection.\n\n- **Opportunity**\n    - **Maurice 'Mo' Adler:** A trash receipt from a local convenience store places Adler in the Bayview District just hours before Mila's body was discovered.\n    - **Tanya Lawson:** Records from Mila's home security system show Lawson had visited the house a few days prior to the incident.\n    - **Erik Stenberg:** Call records indicate that Erik had a heated argument with Mila over the phone right on the night of the murder.\n\n### The Night Of\n\nOn the fateful night of August 2, 2023, Mila Jensen was alone at her residence, completely unaware of the darkness that was about to descend upon her life. Maurice 'Mo' Adler, a notable art critic and one of Mila's staunch critics, harbored deep resentment due to Jensen's rising popularity potentially threatening his influence on art. Adler was sighted in the Bayview District, just hours before the fatal event, as confirmed by a trash receipt from a local convenience store.\n\nAs the night grew darker, Adler seized his opportunity under the guise of a darkness that concealed his intentions at 2035 North Bay Ave. With the Ace Hardware 3/8-Inch x 50-Feet Braided Nylon & Polyester Rope, SKU: ACBRD3850, he ended Mila Jensen's life. Strangulation marks across Mila's neck painted a gruesome picture of the struggles she underwent in her final moments. Adler's final act was a commentary of fear - of an art critic fearing the shift in narrative and artistic power. Survival in this creative field, Adler believed, could only be ensured by eliminating the creative spark that threatened his hold over the art critique landscape.", 'case_characters': [{'sex': 'female', 'role': 'VICTIM', 'age': 32, 'occupation': 'Fine Artist', 'firstName': 'Mila', 'lastName': 'Jensen', 'vices': ['Reclusive', 'Sketchy Relationships'], 'description': 'Mila Jensen, a 32-year-old artist in San Francisco known for her mixed-media creativity, was a petite woman with long auburn hair and ceaseless energy housed in her sparkling eyes. Her introverted, calm, and persistent persona made her an enigma in the art world, often not engaging much with her peers.'}, {'sex': 'male', 'role': 'SUSPECT', 'age': 49, 'occupation': 'Art Critic', 'firstName': 'Maurice', 'lastName': 'Adler', 'vices': ['Smoker', 'Prideful'], 'relationships': [{'Mila Jensen': 'Critic'}], 'description': "Maurice 'Mo' Adler, a 49-year-old prominent art critic known for his harsh reviews, is a tall and broad man carrying an intimidating stature with an intense gaze. His perfectionist personality and dominating presence often stirs unease. He held a professional grudge against Mila after she dismissed his critiques."}, {'sex': 'female', 'role': 'SUSPECT', 'age': 30, 'occupation': 'Fine Artist', 'firstName': 'Tanya', 'lastName': 'Lawson', 'vices': ['Jealousy', 'Ambitious'], 'relationships': [{'Mila Jensen': 'Competitor'}], 'description': "Tanya Lawson, a 30-year-old ambitious fellow artist, is a tall individual with sharp features reflecting her competitive nature. Her fiery red hair complements her fierce personality. Tanya always felt overshadowed by Mila's rapid rise to stardom."}, {'sex': 'male', 'role': 'SUSPECT', 'age': 34, 'occupation': 'Software Developer', 'firstName': 'Erik', 'lastName': 'Stenberg', 'vices': ['Moody', 'Bitterness'], 'relationships': [{'Mila Jensen': 'Ex-Lover'}], 'description': "Erik Stenberg, Mila's ex-boyfriend, is a 34-year-old software developer. He has a lean figure, semi-long brown hair, and soft facial features. Hidden under his usually amiable personality are the bitterness and resentment from the painful breakup."}, {'sex': 'female', 'role': 'WITNESS', 'age': 31, 'occupation': 'Fine Artist', 'firstName': 'Monica', 'lastName': 'Ramirez', 'vices': ['Anxiety', 'Dependent'], 'relationships': [{'Mila Jensen': 'Close Associate'}], 'description': "Monica Ramirez, a 31-year-old artist and a close associate to Mila, is average built with long black hair. She often wears glasses that reflect her anxious and dependent personality. Monica was the one who found Mila’s body after increasingly worrying about Mila's unusual silence."}], 'case_tree': "<BEGIN CONCEPT TREE>\n\n## Root\nMila Jensen was murdered in her San Francisco home, asphyxiated using a nylon rope.\n\n## Branches\n\n1. Concrete evidence:\n     - Means: Death by strangulation using a 3/8-Inch x 50-Feet Braided Nylon & Polyester Rope\n     - Motive: Stemmed from professional competition, professional criticism, and personal conflict\n     - Opportunity: Adler seen nearby hours before, Lawson visited home days prior, Stenberg had heated phone call on the night\n\n2. Character studies:\n     - Mila Jensen: A 32-year-old artist, flourishing in her field, preferring her solitude\n     - Maurice 'Mo' Adler: A 49-year-old renowned art critic, known for his ruthless critiques, held a professional grudge against Jensen\n     - Tanya Lawson: A 30-year-old ambitious fellow artist, felt overshadowed by Jensen's rapidly rising success\n     - Erik Stenberg: A 34-year-old software developer, suffered a recent, bitter breakup with Jensen\n     - Monica Ramirez: A 31-year-old fellow artist, discovered Jensen's body after observing her unusual silence\n     \n3. Police's understanding:\n     - Suspects identified based on motives relating to professional rivalries and personal animosities\n     - The art critic Adler was in the vicinity before the murder\n     - Ramirez placed the distress call at 7:25 PM after finding Jensen's body\n\n4. Ground truth:\n     - Transition of events leading to the discovery of Jensen's murdered body at her residence\n     - Date and time of the murder: August 2, 2023, approximated to take place before 7:25 PM\n     - Jensen's cause of death was asphyxiation by the use of a nylon rope\n\n## Leaves:\n\n1. Concrete evidence:\n     - Nylon rope identified as murder weapon, purchase and possession of which to be probed\n     - Investigation of Adler's presence in the Bayview District hours before the murder\n     - Recording of heated argument between Stenberg and Jensen on the night of the murder\n\n2. Character studies:\n     - Observations of Jensen’s supposed reclusive lifestyle tied against her rising popularity\n     - Adler’s animosity towards Jensen’s dismissive response to his critiques\n     - Lawson’s competition and jealousy hypothesis analyzed against her visit to Jensen’s house a few days prior\n     - Analysis of Stenberg’s recent breakup and its potential connection to the murder\n\n3. Police's understanding:\n     - Evaluation of incoming distress call and Ramirez’s discovery of Jensen’s body\n     - Review of all possible motives behind the murder, establishing a sequence of seemingly hostile events\n     - Probing Adler’s receipt from a local store which pins his location near the scene hours before the incident\n\n4. Ground truth:\n     - Recreating the probable sequence of events on August 2, 2023, based on available circumstantial evidence\n     - Time of death to be cross-verified against Ramirez’s distress call timing\n     - Autopsy report confirming asphyxiation due to strangulation\n\n<END CONCEPT TREE>\n", 'case_solution': "# Solution\n\n## Culprit\nThe murder case has three primary suspects - Maurice 'Mo' Adler, Tanya Lawson, and Erik Stenberg. After careful consideration of all the motivations, available evidence, and timelines, it is evident that Maurice 'Mo' Adler, the renowned art critic, is the culprit in the death of Mila Jensen.\n\n## Means\nThe art critic Adler used an Ace Hardware 3/8-Inch x 50-Feet Braided Nylon & Polyester Rope, SKU: ACBRD3850 to strangle Mila Jensen. This was confirmed during the investigation and subsequently validated by an autopsy report confirming asphyxiation due to strangulation - a detail that aligns with the use of the rope. The rope, thus, was the murder weapon used by Adler to commit the heinous act.\n\n## Motive\nAdler's professional pride was hurt when Mila Jensen dismissed his harsh critiques of her work. As an upcoming artist, Jensen was rapidly gaining popularity, which Adler might have perceived as a threat to his influential position within the art scene. The fear of losing his standing and the resentment against Jensen's dismissive attitude cumulatively built up the motive for Adler to eliminate Jensen.\n\n## Opportunity\nA receipt obtained from a local convenience store placed Maurice 'Mo' Adler in the Bayview District, in the vicinity of Jensen's residence, hours before body was found. This provided him with the golden opportunity to commit the murder. The time elapsed between Adler's appearance in the district and the subsequent distress call made by Ramirez creates a believable time window for Adler to carry out the act and cover his tracks, making him the prime suspect in this murder."}, 'prompt': 'You are a game designer developing crime game. \nYour generations must be compatible with the style presented by the San Francisco Police Department. You present only facts.\nUsing the following crime case:\n\nGiven case details described as this:\n{{case_synopsis_md}}\n\nAnd the list of characters on the case described as this:\n{{case_characters}}\n\nThe case concept tree:\n{{case_tree}}\n\nthe game solution:\n{{case_solution}}\n\n\nConsider a board of UI cards representing evidence.\nThere are 4 tiers and a solution. Each tier is a column in the kanban.\n\nTier 0 is the initial information to flesh out the case. Tier 0 Types: 1. Synopsis 2. Introduction 3. Crime Scene Photo 4. Forensic Reports 5. CCTV photos 6. Witness 7. Victims\n\nTier 1 consists of a Police Interview transcript for each witness and suspect. Some of these may later be converted to audio or video. The number of cards must equal the number of suspects. Invent new suspects with full names, motivations, and relationships to existing characters.\n\nTier 2 provides a clearer picture of motive and the relationships between the suspects, witnesses, victim through their correspondence, interactions, and actions. Tier 2 will provide details to whether alibis are true or the suspects are lying. Tier 2 will provide deeper insight into the personalities of the suspects and victim through their interactions. Tier 2 types include: 1. SMS or other text message types 2. Emails 3. Social media direct messages or posts 4. CCTV photos 5. Voice calls, recordings, and voicemails 6. geolocation or other electronic logging\n\nTier 3 provides evidence that is indisputable and fact based. Tier 3 will provide facts of the case that will subtly reveal discrepancies in the information given by the suspects in Tier 1 and Tier 2. Consider the possibility of documents and facts found by the detectives in a later stage of the case. Tier 3 are more obscure pieces of evidence and could vary wildly depending on the details of the case.\n\nTier 3 must point toward the solution to the case.\nSolution Cards are the last column in the case evidence board and describe the ground truth of what happened, used to power the software.\nThere is a means card, a motive card, an opportunity card and a culprit card.\n\nProvide information following this JSON example:\n{{\n"tiers": [\n{{\n "tier_0": [\n{{"card_type": "card type", "card_text": "card text"}},\n{{{{"card_type": "card type", "card_text": "card text"}}\n]}},\n{{"tier_1": [\n{{{{"card_type": "card type", "card_text": "card text"}},\n{{{{"card_type": "card type", "card_text": "card text"}}\n]}}\n],\n"solutions": [\n{{"means":"mean details"}},\n{{"motive":"motive details"}},\n{{"opportunity":"opportunity details"}},\n{{"culprit":"culprit details"}}\n]\n}}\n\nExample of the generated card:\n{{"card_type": "Physical Evidence", "card_text": "A police evidence photo of the murder weapon, a rusty fishing knife with dried blood on the blade and handle"}}\n\ncreate all tier 3 cards. Generate Solution cards.\ndo not generate tier 0\ndo not generate tier 1\ndo not generate tier 2\n\nreturn only json. do not return any instructions or explanation\n\ndo not say "Json:" start with a bracket or brace.'}
{'solutions': [{'means': 'The artist Mila Jensen was strangled to death. The '
                         'murder weapon, as confirmed by the forensic team, '
                         'was an Ace Hardware 3/8-Inch x 50-Feet Braided Nylon '
                         '& Polyester Rope, SKU: ACBRD3850.'},
               {'motive': "Maurice 'Mo' Adler's professional pride was damaged "
                          'when Mila Jensen dismissed his critiques. His fear '
                          'of losing his influence on the art world due to '
                          "Jensen's rising popularity led him to commit this "
                          'heinous act.'},
               {'opportunity': "Maurice 'Mo' Adler had the perfect "
                               'opportunity, as he was spotted loitering in '
                               "the Bayview District, near Jensen's apartment, "
                               'hours before the discovery of the body. This '
                               'window overlaps with the estimated time of '
                               'murder, giving him enough time to commit the '
                               'murder and leave the scene unnoticed.'},
               {'culprit': 'After examining all the evidence carefully and '
                           "evaluating all the alibis, Maurice 'Mo' Adler is "
                           'revealed as the murderer of Mila Jensen. His '
                           'motive, opportunity, and link to the murder weapon '
                           'point to him as the definitive culprit.'}],
 'tiers': [{'tier_3': [{'card_text': 'A police evidence photo of the Ace '
                                     'Hardware 3/8-Inch x 50-Feet Braided '
                                     'Nylon & Polyester Rope, SKU: ACBRD3850 '
                                     'found near the scene which matches the '
                                     "impression marks on Jensen's neck.",
                        'card_type': 'Physical Evidence'},
                       {'card_text': 'A print out of the call logs showing a '
                                     'gap of one to one and a half hour in '
                                     "Maurice 'Mo' Adler's phone activity "
                                     'around the estimated time of the murder.',
                        'card_type': 'Digital Evidence'},
                       {'card_text': 'A bank transaction evidence showing that '
                                     'Adler had recently purchased a 3/8-Inch '

In [ ]:
prompt = get_prompt(35)
evidence_tier2 = generate_text(prompt, {
    "case_synopsis_md": case_synopsis_md,
    "case_characters": case_characters,
    "case_tree": case_tree,
    "case_solution": case_solution,
    "evidence_tier3": evidence_tier3
    })
# CaseMaker data format required for persisting data
pp.pprint(evidence_tier2)

Prompt: You are a game designer developing crime game.
Your generations must be compatible with the style presented by the San Francisco Police Department. You present only facts.
Using the following crime case:

Given case details described as this:
{{case_synopsis_md}}

And the list of characters on the case described as this:
{{case_characters}}

the original timeline of events:
{{case_tree}}

the game solution:
{{case_solution}}

the tier 3 cards:
{{evidence_tier3}}

Consider a board of UI cards representing evidence.
There are 4 tiers and a solution. Each tier is a column in the kanban.

Tier 0 is the initial information to flesh out the case. Tier 0 Types: 1. Synopsis 2. Introduction 3. Crime Scene Photo 4. Forensic Reports 5. CCTV photos 6. Witness 7. Victims

Tier 1 consists of a Police Interview transcript for each witness and suspect. Some of these may later be converted to audio or video. The number of cards must equal the number of suspects. Invent new suspects with full names, motivations, and relationships to existing characters.

Tier 2 provides a clearer picture of motive and the relationships between the suspects, witnesses, victim through their correspondence, interactions, and actions. Tier 2 will provide details to whether alibis are true or the suspects are lying. Tier 2 will provide deeper insight into the personalities of the suspects and victim through their interactions. Tier 2 types include: 1. SMS or other text message types 2. Emails 3. Social media direct messages or posts 4. CCTV photos 5. Voice calls, recordings, and voicemails 6. geolocation or other electronic logging

Tier 3 provides evidence that is indisputable and fact based. Tier 3 will provide facts of the case that will subtly reveal discrepancies in the information given by the suspects in Tier 1 and Tier 2. Consider the possibility of documents and facts found by the detectives in a later stage of the case. Tier 3 are more obscure pieces of evidence and could vary wildly depending on the details of the case.

Tier 2 provides a clear narrative path to enable to events described in tier 3.

Solution Cards are the last column in the case evidence board and describe the ground truth of what happened, used to power the software.
There is a means card, a motive card, an opportunity card and a culprit card.

Provide information following this JSON example:
{{
"tiers": [
{{
 "tier_0": [
{{"card_type": "card type", "card_text": "card text"}},
{{{{"card_type": "card type", "card_text": "card text"}}
]}},
{{"tier_1": [
{{{{"card_type": "card type", "card_text": "card text"}},
{{{{"card_type": "card type", "card_text": "card text"}}
]}}
],
"solutions": [
{{"means":"mean details"}},
{{"motive":"motive details"}},
{{"opportunity":"opportunity details"}},
{{"culprit":"culprit details"}}
]
}}

Example of the generated card:
{{"card_type": "Police Evidence", "card_text": "A police evidence photo of the murder weapon, a rusty fishing knife with dried blood on the blade and handle"}}

create all tier 2 cards for me.
do not generate tier 0
do not generate tier 1
do not generate tier 3

return only json. do not return any instructions or explanation

do not say Json: please start with a bracket or brace.
Json: {'parameters': {'case_synopsis_md': "### Synopsis\n\nOn the evening of August 2, 2023, Mila Jensen, a 32-year old artist from San Francisco, met her untimely demise due to strangulation. The police received a call at 7:32 PM from her residence at the Bayview District, detailing an alarming occurrence of homicide at 2035 North Bay Ave. The dreadful discovery of Ms. Jensen's lifeless body was made by her close associate, Monica Ramirez, who placed the distress call to the authorities at approximately 7:25 PM. Prior to the horrific incident, unusual silence had prevailed as Ramirez failed to establish contact with Jensen for two days, a deviation from their regular interactions, prompting Monica to investigate in person.\n\n### Characters\n\n- **Mila Jensen** was a rising star in San Francisco's art scene, known for her unique approach to mixed-media sculptural creations. She led a reclusive lifestyle at the house where her body was found.\n\n- **Maurice 'Mo' Adler** is a prominent art critic known for his harsh reviews of contemporary works, including those of Mila Jensen.\n\n- **Tanya Lawson** is an ambitious fellow artist, a competitor in the creative field who often felt overshadowed by Ms. Jensen's success.\n\n- **Erik Stenberg** had been Ms. Jensen's romantic partner until their recent, bitter breakup.\n\n- **Monica Ramirez** is a fellow artist, and the one who found Ms. Jensen's body after two days of no contact.\n\n### Means, Motive & Opportunity\n\n- **Means:** Mila Jensen was brutally strangled using a nylon rope, specifically the Ace Hardware 3/8-Inch x 50-Feet Braided Nylon & Polyester Rope, SKU: ACBRD3850.\n\n- **Motive**\n    - **Maurice 'Mo' Adler:** His professional pride was hurt by Ms. Jensen's dismissive response to his critiques; He had possibly feared Ms. Jensen's growing influence on artistic norms.\n    - **Tanya Lawson:** Her growing resentment due to Jenkins' rapid rise to stardom; She had potentially perceived Mila's successes as hindrances to her own.\n    - **Erik Stenberg:** Their recent breakup might have stirred up feelings of resentment and anger; Erik might have harbored resentment due to perceived rejection.\n\n- **Opportunity**\n    - **Maurice 'Mo' Adler:** A trash receipt from a local convenience store places Adler in the Bayview District just hours before Mila's body was discovered.\n    - **Tanya Lawson:** Records from Mila's home security system show Lawson had visited the house a few days prior to the incident.\n    - **Erik Stenberg:** Call records indicate that Erik had a heated argument with Mila over the phone right on the night of the murder.\n\n### The Night Of\n\nOn the fateful night of August 2, 2023, Mila Jensen was alone at her residence, completely unaware of the darkness that was about to descend upon her life. Maurice 'Mo' Adler, a notable art critic and one of Mila's staunch critics, harbored deep resentment due to Jensen's rising popularity potentially threatening his influence on art. Adler was sighted in the Bayview District, just hours before the fatal event, as confirmed by a trash receipt from a local convenience store.\n\nAs the night grew darker, Adler seized his opportunity under the guise of a darkness that concealed his intentions at 2035 North Bay Ave. With the Ace Hardware 3/8-Inch x 50-Feet Braided Nylon & Polyester Rope, SKU: ACBRD3850, he ended Mila Jensen's life. Strangulation marks across Mila's neck painted a gruesome picture of the struggles she underwent in her final moments. Adler's final act was a commentary of fear - of an art critic fearing the shift in narrative and artistic power. Survival in this creative field, Adler believed, could only be ensured by eliminating the creative spark that threatened his hold over the art critique landscape.", 'case_characters': [{'sex': 'female', 'role': 'VICTIM', 'age': 32, 'occupation': 'Fine Artist', 'firstName': 'Mila', 'lastName': 'Jensen', 'vices': ['Reclusive', 'Sketchy Relationships'], 'description': 'Mila Jensen, a 32-year-old artist in San Francisco known for her mixed-media creativity, was a petite woman with long auburn hair and ceaseless energy housed in her sparkling eyes. Her introverted, calm, and persistent persona made her an enigma in the art world, often not engaging much with her peers.'}, {'sex': 'male', 'role': 'SUSPECT', 'age': 49, 'occupation': 'Art Critic', 'firstName': 'Maurice', 'lastName': 'Adler', 'vices': ['Smoker', 'Prideful'], 'relationships': [{'Mila Jensen': 'Critic'}], 'description': "Maurice 'Mo' Adler, a 49-year-old prominent art critic known for his harsh reviews, is a tall and broad man carrying an intimidating stature with an intense gaze. His perfectionist personality and dominating presence often stirs unease. He held a professional grudge against Mila after she dismissed his critiques."}, {'sex': 'female', 'role': 'SUSPECT', 'age': 30, 'occupation': 'Fine Artist', 'firstName': 'Tanya', 'lastName': 'Lawson', 'vices': ['Jealousy', 'Ambitious'], 'relationships': [{'Mila Jensen': 'Competitor'}], 'description': "Tanya Lawson, a 30-year-old ambitious fellow artist, is a tall individual with sharp features reflecting her competitive nature. Her fiery red hair complements her fierce personality. Tanya always felt overshadowed by Mila's rapid rise to stardom."}, {'sex': 'male', 'role': 'SUSPECT', 'age': 34, 'occupation': 'Software Developer', 'firstName': 'Erik', 'lastName': 'Stenberg', 'vices': ['Moody', 'Bitterness'], 'relationships': [{'Mila Jensen': 'Ex-Lover'}], 'description': "Erik Stenberg, Mila's ex-boyfriend, is a 34-year-old software developer. He has a lean figure, semi-long brown hair, and soft facial features. Hidden under his usually amiable personality are the bitterness and resentment from the painful breakup."}, {'sex': 'female', 'role': 'WITNESS', 'age': 31, 'occupation': 'Fine Artist', 'firstName': 'Monica', 'lastName': 'Ramirez', 'vices': ['Anxiety', 'Dependent'], 'relationships': [{'Mila Jensen': 'Close Associate'}], 'description': "Monica Ramirez, a 31-year-old artist and a close associate to Mila, is average built with long black hair. She often wears glasses that reflect her anxious and dependent personality. Monica was the one who found Mila’s body after increasingly worrying about Mila's unusual silence."}], 'case_tree': "<BEGIN CONCEPT TREE>\n\n## Root\nMila Jensen was murdered in her San Francisco home, asphyxiated using a nylon rope.\n\n## Branches\n\n1. Concrete evidence:\n     - Means: Death by strangulation using a 3/8-Inch x 50-Feet Braided Nylon & Polyester Rope\n     - Motive: Stemmed from professional competition, professional criticism, and personal conflict\n     - Opportunity: Adler seen nearby hours before, Lawson visited home days prior, Stenberg had heated phone call on the night\n\n2. Character studies:\n     - Mila Jensen: A 32-year-old artist, flourishing in her field, preferring her solitude\n     - Maurice 'Mo' Adler: A 49-year-old renowned art critic, known for his ruthless critiques, held a professional grudge against Jensen\n     - Tanya Lawson: A 30-year-old ambitious fellow artist, felt overshadowed by Jensen's rapidly rising success\n     - Erik Stenberg: A 34-year-old software developer, suffered a recent, bitter breakup with Jensen\n     - Monica Ramirez: A 31-year-old fellow artist, discovered Jensen's body after observing her unusual silence\n     \n3. Police's understanding:\n     - Suspects identified based on motives relating to professional rivalries and personal animosities\n     - The art critic Adler was in the vicinity before the murder\n     - Ramirez placed the distress call at 7:25 PM after finding Jensen's body\n\n4. Ground truth:\n     - Transition of events leading to the discovery of Jensen's murdered body at her residence\n     - Date and time of the murder: August 2, 2023, approximated to take place before 7:25 PM\n     - Jensen's cause of death was asphyxiation by the use of a nylon rope\n\n## Leaves:\n\n1. Concrete evidence:\n     - Nylon rope identified as murder weapon, purchase and possession of which to be probed\n     - Investigation of Adler's presence in the Bayview District hours before the murder\n     - Recording of heated argument between Stenberg and Jensen on the night of the murder\n\n2. Character studies:\n     - Observations of Jensen’s supposed reclusive lifestyle tied against her rising popularity\n     - Adler’s animosity towards Jensen’s dismissive response to his critiques\n     - Lawson’s competition and jealousy hypothesis analyzed against her visit to Jensen’s house a few days prior\n     - Analysis of Stenberg’s recent breakup and its potential connection to the murder\n\n3. Police's understanding:\n     - Evaluation of incoming distress call and Ramirez’s discovery of Jensen’s body\n     - Review of all possible motives behind the murder, establishing a sequence of seemingly hostile events\n     - Probing Adler’s receipt from a local store which pins his location near the scene hours before the incident\n\n4. Ground truth:\n     - Recreating the probable sequence of events on August 2, 2023, based on available circumstantial evidence\n     - Time of death to be cross-verified against Ramirez’s distress call timing\n     - Autopsy report confirming asphyxiation due to strangulation\n\n<END CONCEPT TREE>\n", 'case_solution': "# Solution\n\n## Culprit\nThe murder case has three primary suspects - Maurice 'Mo' Adler, Tanya Lawson, and Erik Stenberg. After careful consideration of all the motivations, available evidence, and timelines, it is evident that Maurice 'Mo' Adler, the renowned art critic, is the culprit in the death of Mila Jensen.\n\n## Means\nThe art critic Adler used an Ace Hardware 3/8-Inch x 50-Feet Braided Nylon & Polyester Rope, SKU: ACBRD3850 to strangle Mila Jensen. This was confirmed during the investigation and subsequently validated by an autopsy report confirming asphyxiation due to strangulation - a detail that aligns with the use of the rope. The rope, thus, was the murder weapon used by Adler to commit the heinous act.\n\n## Motive\nAdler's professional pride was hurt when Mila Jensen dismissed his harsh critiques of her work. As an upcoming artist, Jensen was rapidly gaining popularity, which Adler might have perceived as a threat to his influential position within the art scene. The fear of losing his standing and the resentment against Jensen's dismissive attitude cumulatively built up the motive for Adler to eliminate Jensen.\n\n## Opportunity\nA receipt obtained from a local convenience store placed Maurice 'Mo' Adler in the Bayview District, in the vicinity of Jensen's residence, hours before body was found. This provided him with the golden opportunity to commit the murder. The time elapsed between Adler's appearance in the district and the subsequent distress call made by Ramirez creates a believable time window for Adler to carry out the act and cover his tracks, making him the prime suspect in this murder.", 'evidence_tier3': {'tiers': [{'tier_3': [{'card_type': 'Physical Evidence', 'card_text': "A receipt found at the crime scene from a local convenience store in the Bayview District with Maurice 'Mo' Adler's credit card information dated the day of the murder"}, {'card_type': 'Forensics Report', 'card_text': "Forensics report confirms cause of death as asphyxiation. Minute fibers from the Ace Hardware 3/8-Inch x 50-Feet Braided Nylon & Polyester Rope, SKU: ACBRD3850 were found embedded on the victim's neck."}, {'card_type': 'Police Report', 'card_text': 'Call records reveal Erik Stenberg had a heated argument with the victim on the night of the murder, however there is no physical evidence linking him to the crime.'}, {'card_type': 'Digital Evidence', 'card_text': "Security footage from the nearby convenience store, timestamped just hours before the body was discovered, shows Maurice 'Mo' Adler purchasing the Ace Hardware 3/8-Inch x 50-Feet Braided Nylon & Polyester Rope, SKU: ACBRD3850."}, {'card_type': 'Digital Evidence', 'card_text': "Security logs from Mila's home automation system show no other visitors aside from Tanya Lawson, a few days prior to the incident. There is no record of her visit on the day of the murder."}]}], 'solutions': [{'means': "Maurice 'Mo' Adler strangled Mila using an Ace Hardware 3/8-Inch x 50-Feet Braided Nylon & Polyester Rope, SKU: ACBRD3850."}, {'motive': "Adler's pride was hurt when Mila dismissed his critiques. He feared Mila's growing influence on artistic norms and was threatened by her success."}, {'opportunity': "A receipt places Adler in the Bayview District, near Mila's residence, just hours before her body was discovered."}, {'culprit': "Maurice 'Mo' Adler, the renowned art critic, is the murderer."}]}}, 'prompt': 'You are a game designer developing crime game. \nYour generations must be compatible with the style presented by the San Francisco Police Department. You present only facts.\nUsing the following crime case:\n\nGiven case details described as this:\n{{case_synopsis_md}}\n\nAnd the list of characters on the case described as this:\n{{case_characters}}\n\nthe original timeline of events:\n{{case_tree}}\n\nthe game solution:\n{{case_solution}}\n\nthe tier 3 cards:\n{{evidence_tier3}}\n\nConsider a board of UI cards representing evidence.\nThere are 4 tiers and a solution. Each tier is a column in the kanban.\n\nTier 0 is the initial information to flesh out the case. Tier 0 Types: 1. Synopsis 2. Introduction 3. Crime Scene Photo 4. Forensic Reports 5. CCTV photos 6. Witness 7. Victims\n\nTier 1 consists of a Police Interview transcript for each witness and suspect. Some of these may later be converted to audio or video. The number of cards must equal the number of suspects. Invent new suspects with full names, motivations, and relationships to existing characters.\n\nTier 2 provides a clearer picture of motive and the relationships between the suspects, witnesses, victim through their correspondence, interactions, and actions. Tier 2 will provide details to whether alibis are true or the suspects are lying. Tier 2 will provide deeper insight into the personalities of the suspects and victim through their interactions. Tier 2 types include: 1. SMS or other text message types 2. Emails 3. Social media direct messages or posts 4. CCTV photos 5. Voice calls, recordings, and voicemails 6. geolocation or other electronic logging\n\nTier 3 provides evidence that is indisputable and fact based. Tier 3 will provide facts of the case that will subtly reveal discrepancies in the information given by the suspects in Tier 1 and Tier 2. Consider the possibility of documents and facts found by the detectives in a later stage of the case. Tier 3 are more obscure pieces of evidence and could vary wildly depending on the details of the case.\n\nTier 2 provides a clear narrative path to enable to events described in tier 3.\n\nSolution Cards are the last column in the case evidence board and describe the ground truth of what happened, used to power the software.\nThere is a means card, a motive card, an opportunity card and a culprit card.\n\nProvide information following this JSON example:\n{{\n"tiers": [\n{{\n "tier_0": [\n{{"card_type": "card type", "card_text": "card text"}},\n{{{{"card_type": "card type", "card_text": "card text"}}\n]}},\n{{"tier_1": [\n{{{{"card_type": "card type", "card_text": "card text"}},\n{{{{"card_type": "card type", "card_text": "card text"}}\n]}}\n],\n"solutions": [\n{{"means":"mean details"}},\n{{"motive":"motive details"}},\n{{"opportunity":"opportunity details"}},\n{{"culprit":"culprit details"}}\n]\n}}\n\nExample of the generated card:\n{{"card_type": "Police Evidence", "card_text": "A police evidence photo of the murder weapon, a rusty fishing knife with dried blood on the blade and handle"}}\n\ncreate all tier 2 cards for me.\ndo not generate tier 0\ndo not generate tier 1\ndo not generate tier 3\n\nreturn only json. do not return any instructions or explanation\n\ndo not say Json: please start with a bracket or brace.'}
{'tiers': [{'tier_2': [{'card_text': 'Mila Jensen posted on her social media '
                                     "saying, 'Art is about breaking norms, "
                                     'not maintaining them. Always '
                                     "remember...' three days before the "
                                     'murder, possibly a response to Adler’s '
                                     'critique.',
                        'card_type': 'Social Media Post'},
                       {'card_text': 'Text messages reveal an escalating '
                                     'argument between Erick Stenberg and Mila '

In [ ]:
prompt = get_prompt(36)
evidence_tier1 = generate_text(prompt, {
    "case_synopsis_md": case_synopsis_md,
    "case_characters": case_characters,
    "case_tree": case_tree,
    "case_solution": case_solution,
    "evidence_tier3": evidence_tier3,
    "evidence_tier2": evidence_tier2
    })
# CaseMaker data format required for persisting data
pp.pprint(evidence_tier1)

Prompt: You are a game designer developing crime game. Using the following crime case:

Your generations must be compatible with the style presented by the San Francisco Police Department. You present only facts.

Given the case synopsis:
{{case_synopsis_md}}

And the list of characters on the case described as this:
{{case_characters}}

the concept tree:
{{case_tree}}

the game solution:
{{case_solution}}

the prior cards:
{{evidence_tier2}}
{{evidence_tier3}}

Consider a board of UI cards representing evidence.
There are 4 tiers and a solution. Each tier is a column in the kanban.

Tier 0 is the initial information to flesh out the case. Tier 0 Types: 1. Synopsis 2. Introduction 3. Crime Scene Photo 4. Forensic Reports 5. CCTV photos 6. Witness 7. Victims

Tier 1 consists of a Police Interview transcript for each witness and suspect. Some of these may later be converted to audio or video. The number of cards must equal the number of suspects. Invent new suspects with full names, motivations, and relationships to existing characters.

Tier 2 provides a clearer picture of motive and the relationships between the suspects, witnesses, victim through their correspondence, interactions, and actions. Tier 2 will provide details to whether alibis are true or the suspects are lying. Tier 2 will provide deeper insight into the personalities of the suspects and victim through their interactions. Tier 2 types include: 1. SMS or other text message types 2. Emails 3. Social media direct messages or posts 4. CCTV photos 5. Voice calls, recordings, and voicemails 6. geolocation or other electronic logging

Tier 3 provides evidence that is indisputable and fact based. Tier 3 will provide facts of the case that will subtly reveal discrepancies in the information given by the suspects in Tier 1 and Tier 2. Consider the possibility of documents and facts found by the detectives in a later stage of the case. Tier 3 are more obscure pieces of evidence and could vary wildly depending on the details of the case.


Solution Cards are the last column in the case evidence board and describe the ground truth of what happened, used to power the software.
There is a means card, a motive card, an opportunity card and a culprit card.

Provide information following this JSON example:
{{
"tiers": [
{{
 "tier_0": [
{{"card_type": "card type", "card_text": "card text"}},
{{{{"card_type": "card type", "card_text": "card text"}}
]}},
{{"tier_1": [
{{{{"card_type": "card type", "card_text": "card text"}},
{{{{"card_type": "card type", "card_text": "card text"}}
]}}
],
"solutions": [
{{"means":"mean details"}},
{{"motive":"motive details"}},
{{"opportunity":"opportunity details"}},
{{"culprit":"culprit details"}}
]
}}

Example of the generated card:
{{"card_type": "Police Evidence", "card_text": "A police evidence photo of the murder weapon, a rusty fishing knife with dried blood on the blade and handle"}}

create all tier 1 police interview cards for me. Provide a goal for both the detective and the interview subject.
do not generate tier 0
do not generate tier 2
do not generate tier 3

return only json. do not return any instructions or explanation

do not say Json: please start with a bracket or brace.

In [ ]:
prompt = get_prompt(38)
evidence_tier0 = generate_text(prompt, {
    "case_synopsis_md": case_synopsis_md,
    "case_characters": case_characters,
    "case_tree": case_tree,
    "case_solution": case_solution,
    "evidence_tier3": evidence_tier3,
    "evidence_tier2": evidence_tier2,
    "evidence_tier1": evidence_tier1,
    })
# CaseMaker data format required for persisting data
pp.pprint(evidence_tier0)

KeyError: ignored

In [ ]:
prompt = get_prompt(39)
prosecutor_validator = generate_text(prompt, {
    "evidence_tier3": evidence_tier3,
    "evidence_tier2": evidence_tier2,
    "evidence_tier1": evidence_tier1,
    "evidence_tier0": evidence_tier0,
    })
# CaseMaker data format required for persisting data
md(prosecutor_validator)

KeyError: ignored

# NEEDS UPDATING
Here is how output of evidences are being mapped for UI / Database needs.

In [ ]:
import uuid

tiers = list(map(lambda t: next(iter(t.keys())), evidences["tiers"]))
tiers.append('Solutions')

cards = []

for tier in evidences["tiers"]:
  for key in tier.keys():
    for card in tier[key]:
      mapped_card = {"card_type": card["card_type"], "card_text": card["card_text"], "tier": key, "uid": str(uuid.uuid4().hex)}
      cards.append(mapped_card)

for solution in evidences["solutions"]:
  for key, value in solution.items():
    mapped_card = {"card_type": key, "card_text": value, "tier": "Solution", "uid": str(uuid.uuid4().hex)}
    cards.append(mapped_card)

casemaker_evidence_list = list(
    map(
        lambda card: {
            "uid": card["uid"],
            "name": card["card_type"],
            "description": '',
            "type": 'TEXT',
            "tier": card["tier"],
            "data": {
                "value": card["card_text"],
                "description": ''
            },
            "propertyGenerationStatus": 'INITIAL',
            "propertiesType": 'NONE',
            "relations": [],
            "properties": []
        },
        cards
    )
)

casemaker_evidence_board = { # CaseMaker data format required for persisting data
    "characteristics": casemaker_evidence_list,
    "tiers": tiers
}
pp.pprint(casemaker_evidence_board)

NameError: ignored

In [18]:
events = [
  {
    "name": "Murder scene: Alex Duran kills Marisol Vega",
    "description": "On the night of September 9th, 2023, Marisol Vega visited The Gilded Palace, a bar in San Francisco. There, she encountered Alex Duran, a bartender with whom she had a past dispute. As the night went on, Duran's anger towards Vega grew. After Vega left the bar, Duran followed her home. Meanwhile, Leonel Graves, a former member of Vega's inner circle, was observed nearby the murder location, having coincidentally run into Vega earlier in the evening. However, it was Alex Duran who forced his way into Vega's residence and used a length of high-tensile strength nylon rope to strangle her to death. The murder took place at 1466 34th Ave in the Northern Police District. Juanita Vega, Marisol's sister and housemate, discovered her lifeless body and called the authorities. The evidence collected by law enforcement, along with Duran's visible agitation that night, pointed to his guilt in the crime.",
    "datetime": "PLACEHOLDER",
    "category": "EVENT",
    "charactersOnCasesUid": "",
    "era": 0,
    "job": "",
    "characters": [
      "Marisol Vega",
      "Alex Duran"
    ]
  },
  {
    "name": "Marisol Vega: victim start scene",
    "description": "The victim, Marisol Vega, was a 28-year-old woman. She was a Cardiothoracic Surgeon and had a successful career in the medical field. Marisol had fiery red hair and icy blue eyes, which made her stand out in a crowd. She was known for her imposing figure and contrasting features. Marisol had an estranged ex-girlfriend named Rose Hawthorne, who was also a suspect in her murder. Their relationship had collapsed, leaving Rose with profound jealousy and bitterness. Marisol's breakup with Rose pushed her towards a life of solitude. Despite the end of their relationship, Rose struggled to control Marisol's life and resorted to manipulative tactics. Marisol's success and independence seemed to exacerbate Rose's feelings of resentment. Marisol's friends described her as a strong-willed and determined individual. She was well-respected in her profession and had a close circle of friends. However, one of her friends, Leonel Graves, also became a suspect in her murder. Leonel was a 33-year-old Event Planner who was once a valued member of Marisol's circle. However, he was excluded from the group, which fueled his bitterness and resentment towards Marisol. Leonel had lonesome brown eyes and a thinning black beard. He was known for his quick thinking and innovative approaches to his profession. Both Rose and Leonel had motives for seeking retribution against Marisol, making them prime suspects in her murder.",
    "datetime": "PLACEHOLDER",
    "category": "EVENT",
    "charactersOnCasesUid": "",
    "era": -6,
    "job": "",
    "characters": [
      "Marisol Vega"
    ]
  },
  {
    "name": "Rose Hawthorne had no opportunity",
    "description": "Based on the evidence collected at the murder scene, it is clear that Dr. Rose Hawthorne, the suspect, could not have had the opportunity to commit the murder. The crime took place at 1466 34th Ave in the Northern Police District, while Dr. Hawthorne's occupation as a Cardiothoracic Surgeon would require her to be at a hospital or medical facility during the time of the murder. Additionally, the description of the crime states that Alex Duran, not Dr. Hawthorne, forced his way into Marisol Vega's residence and used a length of high-tensile strength nylon rope to strangle her to death. Therefore, Dr. Rose Hawthorne's presence at the murder scene is not possible, and she should be considered innocent in this case.",
    "datetime": "PLACEHOLDER",
    "category": "OPPORTUNITY",
    "charactersOnCasesUid": "",
    "era": 0,
    "job": "Rose Hawthorne truth opp",
    "characters": [
      "Rose Hawthorne"
    ]
  },
  {
    "name": "Leonel Graves had no opportunity",
    "description": "Based on the evidence collected at the murder scene, it is clear that our suspect, Leonel Graves, could not have had the opportunity to commit the murder. The murder took place at Marisol Vega's residence, where Alex Duran, a bartender with a past dispute with Vega, forced his way in and strangled her to death using a length of high-tensile strength nylon rope. \n\nLeonel Graves, on the other hand, was observed nearby the murder location earlier in the evening, having coincidentally run into Vega. However, there is no evidence linking him to the actual crime scene or the murder weapon. \n\nFurthermore, the description of Leonel Graves as an Event Planner does not provide him with the necessary skills or knowledge to carry out such a violent and calculated murder. His profession and background do not align with the methods used in this crime. \n\nTherefore, based on the evidence and the lack of opportunity, it is clear that Leonel Graves could not have had the opportunity to kill Marisol Vega.",
    "datetime": "PLACEHOLDER",
    "category": "OPPORTUNITY",
    "charactersOnCasesUid": "",
    "era": 0,
    "job": "Leonel Graves truth opp",
    "characters": [
      "Leonel Graves"
    ]
  },
  {
    "name": "Rose Hawthorne maybe had opportunity",
    "description": "Based on the evidence collected at the murder scene, it is clear that Dr. Rose Hawthorne, the suspect, could not have had the opportunity to commit the murder. The crime took place at 1466 34th Ave in the Northern Police District, while Dr. Hawthorne's occupation as a Cardiothoracic Surgeon would require her to be at a hospital or medical facility during the time of the murder. Additionally, the description of the crime states that Alex Duran, not Dr. Hawthorne, forced his way into Marisol Vega's residence and used a length of high-tensile strength nylon rope to strangle her to death. Therefore, Dr. Rose Hawthorne's presence at the murder scene is not possible, and she should be considered innocent in this case.",
    "datetime": "PLACEHOLDER",
    "category": "OPPORTUNITY",
    "charactersOnCasesUid": "",
    "era": -2,
    "job": "Rose Hawthorne false_positive opp",
    "characters": [
      "Rose Hawthorne"
    ]
  },
  {
    "name": "Leonel Graves maybe had opportunity",
    "description": "Leonel Graves, the suspect in the murder case, had no opportunity to commit the crime. The murder took place at Marisol Vega's residence, where Alex Duran, a bartender with a past dispute with Vega, forced his way in and strangled her to death using a length of high-tensile strength nylon rope. Leonel Graves was observed nearby the murder location earlier in the evening, coincidentally running into Vega. However, there is no evidence linking him to the actual crime scene or the murder weapon. Additionally, Leonel Graves' profession as an Event Planner does not provide him with the necessary skills or knowledge to carry out such a violent and calculated murder. Based on the evidence and the lack of opportunity, it is clear that Leonel Graves could not have had the opportunity to kill Marisol Vega.",
    "datetime": "PLACEHOLDER",
    "category": "OPPORTUNITY",
    "charactersOnCasesUid": "",
    "era": -1,
    "job": "Leonel Graves false_positive opp",
    "characters": [
      "Leonel Graves"
    ]
  },
  {
    "name": "Rose Hawthorne had the means",
    "description": "On the night of September 9th, 2023, Marisol Vega visited The Gilded Palace, a bar in San Francisco. There, she encountered Alex Duran, a bartender with whom she had a past dispute. As the night went on, Duran's anger towards Vega grew. After Vega left the bar, Duran followed her home. Meanwhile, Leonel Graves, a former member of Vega's inner circle, was observed nearby the murder location, having coincidentally run into Vega earlier in the evening. However, it was Alex Duran who forced his way into Vega's residence and used a length of high-tensile strength nylon rope to strangle her to death. The murder took place at 1466 34th Ave in the Northern Police District. Juanita Vega, Marisol's sister and housemate, discovered her lifeless body and called the authorities. The evidence collected by law enforcement, along with Duran's visible agitation that night, pointed to his guilt in the crime.",
    "datetime": "PLACEHOLDER",
    "category": "MEANS",
    "charactersOnCasesUid": "",
    "era": -5,
    "job": "Rose Hawthorne truth means",
    "characters": [
      "Rose Hawthorne"
    ]
  },
  {
    "name": "Leonel Graves had the means",
    "description": "On the night of September 9th, 2023, Marisol Vega visited The Gilded Palace, a bar in San Francisco. There, she encountered Alex Duran, a bartender with whom she had a past dispute. As the night went on, Duran's anger towards Vega grew. After Vega left the bar, Duran followed her home. Meanwhile, Leonel Graves, a former member of Vega's inner circle, was observed nearby the murder location, having coincidentally run into Vega earlier in the evening. However, it was Alex Duran who forced his way into Vega's residence and used a length of high-tensile strength nylon rope to strangle her to death. The murder took place at 1466 34th Ave in the Northern Police District. Juanita Vega, Marisol's sister and housemate, discovered her lifeless body and called the authorities. The evidence collected by law enforcement, along with Duran's visible agitation that night, pointed to his guilt in the crime.",
    "datetime": "PLACEHOLDER",
    "category": "MEANS",
    "charactersOnCasesUid": "",
    "era": -6,
    "job": "Leonel Graves truth means",
    "characters": [
      "Leonel Graves"
    ]
  },
  {
    "name": "Rose Hawthorne had a motive",
    "description": "During the evening of September 9th, 2023, Dr. Rose Hawthorne, the suspect in Marisol Vega's murder, was on duty at St. Mary's Hospital. As a Cardiothoracic Surgeon, Dr. Hawthorne had a demanding schedule and was required to be present at the hospital during the time of the murder. Multiple witnesses, including her colleagues and patients, can confirm that Dr. Hawthorne was performing a life-saving surgery that evening. The surgery lasted for several hours, providing Dr. Hawthorne with a solid alibi. The hospital records and testimonies from the medical staff corroborate her presence and involvement in the surgery. Therefore, it is impossible for Dr. Hawthorne to have been at the murder scene and she should be considered innocent in this case.",
    "datetime": "PLACEHOLDER",
    "category": "MOTIVE",
    "charactersOnCasesUid": "",
    "era": -3,
    "job": "Rose Hawthorne truth motive",
    "characters": [
      "Rose Hawthorne",
      "Marisol Vega"
    ]
  },
  {
    "name": "Leonel Graves had a motive",
    "description": "Marisol Vega's estranged ex-girlfriend, Rose Hawthorne, had an unhealthy obsession with her. Despite their breakup, Rose struggled to let go of Marisol and resorted to manipulative tactics to control her. She would often stalk Marisol, tracking her every move and monitoring her social media accounts. Rose's jealousy and bitterness towards Marisol's success and independence grew over time. This obsession and resentment gave Rose a motive to seek retribution against Marisol, making her a prime suspect in her murder.",
    "datetime": "PLACEHOLDER",
    "category": "MOTIVE",
    "charactersOnCasesUid": "",
    "era": -2,
    "job": "Leonel Graves truth motive",
    "characters": [
      "Leonel Graves",
      "Marisol Vega"
    ]
  }
]

In [30]:
# Evaluation

def events2df(events):
    character2events = {}

    for event in events:
        characters = event["characters"]
        for character in characters:
            if character not in character2events:
                character2events[character] = {
                    "character": character,
                    -6: "",
                    -5: "",
                    -4: "",
                    -3: "",
                    -2: "",
                    -1: "",
                    0: "",
                }
            era = event["era"]
            character2events[character][era] = (
                event["name"] + "\n\n" + event["description"] + "\n\n" + event["job"]
            )

    # print(character2events)

    df = pd.DataFrame(character2events.values())
    df = df[["character", -6, -5, -4, -3, -2, -1, 0]]
    return df

def pretty_print(df):
    return display(HTML(df.to_html().replace("\\n", "<br>")))

def events2timeline(events):
    df = events2df(events)
    pretty_print(df)

events2timeline(events)